### ISSUE TITLE
Unicode error

### ISSUE THREAD

**Issue by antocuni** [pdbpp/pdbpp#15]
Originally reported by: **Julien Phalip (Bitbucket: [jphalip](https://bitbucket.org/jphalip), GitHub: [jphalip](https://github.com/jphalip))**

----------------------------------------

If I run this script using pdbpp:

    
    #!python
    
    # -*- coding: utf-8 -*-
    import pdb; pdb.set_trace()
    s = u'This is a some text without accent'
    s = u'This is some text with an accent: à'
    s = u'This is some other text'
    

... and press 'n', I get this error:

    
    $ python test.py
    > /Users/julien/Documents/Development/eclipse/workspace/iwc/djangosite/test.py(3)<module>()
    -> s = 'This is a some text without accent'
    (Pdb++) n
    > Traceback (most recent call last):
      File "test.py", line 4, in <module>
        s = 'This is some text with an accent: à'
      File "test.py", line 4, in <module>
        s = 'This is some text with an accent: à'
      File "/System/Library/Frameworks/Python.framework/Versions/2.6/lib/python2.6/bdb.py", line 46, in trace_dispatch
        return self.dispatch_line(frame)
      File "/System/Library/Frameworks/Python.framework/Versions/2.6/lib/python2.6/bdb.py", line 64, in dispatch_line
        self.user_line(frame)
      File "/System/Library/Frameworks/Python.framework/Versions/2.6/lib/python2.6/pdb.py", line 150, in user_line
        self.interaction(frame, None)
      File "/Users/julien/.virtualenvs/iwc/lib/python2.6/site-packages/pdbpp-0.7.2-py2.6.egg/pdb.py", line 142, in interaction
        self.print_stack_entry(self.stack[self.curindex])
      File "/System/Library/Frameworks/Python.framework/Versions/2.6/lib/python2.6/pdb.py", line 882, in print_stack_entry
        prompt_prefix)
      File "/Users/julien/.virtualenvs/iwc/lib/python2.6/codecs.py", line 351, in write
        data, consumed = self.encode(object, self.errors)
    UnicodeDecodeError: 'ascii' codec can't decode byte 0xc3 in position 158: ordinal not in range(128)
    

So unfortunately I can't use pdbpp with any code that contains unicode characters.

----------------------------------------
- Bitbucket: https://bitbucket.org/antocuni/pdb/issue/15

**Comment by antocuni** [comment]
*Original comment by* **Antonio Cuni (Bitbucket: [antocuni](https://bitbucket.org/antocuni), GitHub: [antocuni](https://github.com/antocuni))**:

----------------------------------------

fix issue #15

this needs a bit of explanation: it's a problem which happens also in plain
pdb, because it reads source files as str and try to prints them on stdout
without doing any decoding/encoding. So, if stdout has a different encoding
than the source, you get bad characters.

The proper fix would be to detect the encoding from the magic comment in the
file (e.g. "# -*- encoding: utf-8 -*-"). However, there is no easy way in the
stdlib to do it, so I opted for something simpler: we try to decode the source
by trying one after the other the encodings specified in the configurable
option config.encodings, which defaults to ('utf-8', 'latin-1'). This should
work in most cases.
