### ISSUE TITLE
crash when printing arguments and one of them is an invalid bytestream

### ISSUE THREAD

**Issue by antocuni** [pdbpp/pdbpp#29]
Originally reported by: **Martin Matusiak (Bitbucket: [numerodix](https://bitbucket.org/numerodix), GitHub: [numerodix](https://github.com/numerodix))**

----------------------------------------

I was calling a function with the argument "\xff\xfe", which is invalid utf8 (on purpose, as it happens). When I use the "args" command pdb++ tries to print this argument and crashes with a stacktrace:

```
#!python

bstring = Traceback (most recent call last):
  File "test.py", line 105, in <module>
    main()
  File "test.py", line 70, in main
    assert_bad('\xff\xfe')
  File "test.py", line 38, in assert_bad
    def assert_bad(bstring):
  File "/usr/lib/python2.7/bdb.py", line 51, in trace_dispatch
    return self.dispatch_call(frame, arg)
  File "/usr/lib/python2.7/bdb.py", line 80, in dispatch_call
    self.user_call(frame, arg)
  File "/usr/lib/python2.7/pdb.py", line 148, in user_call
    self.interaction(frame, None)
  File "/home/alex/envs/pdbpp/local/lib/python2.7/site-packages/pdbpp-0.7.2-py2.7.egg/pdb.py", line 148, in interaction
    self.cmdloop()
  File "/usr/lib/python2.7/cmd.py", line 142, in cmdloop
    stop = self.onecmd(line)
  File "/usr/lib/python2.7/pdb.py", line 279, in onecmd
    return cmd.Cmd.onecmd(self, line)
  File "/usr/lib/python2.7/cmd.py", line 221, in onecmd
    return func(arg)
  File "/usr/lib/python2.7/pdb.py", line 747, in do_args
    if name in dict: print >>self.stdout, dict[name]
  File "/home/alex/envs/pdbpp/lib/python2.7/codecs.py", line 351, in write
    data, consumed = self.encode(object, self.errors)
UnicodeDecodeError: 'ascii' codec can't decode byte 0xff in position 0: ordinal not in range(128)

```

When I try this in native pdb it fails gracefully:

```
#!python

-> assert_bad('\xff\xfe')
(Pdb) s
--Call--
> /home/alex/code/haskplay/utf8/test.py(38)assert_bad()
-> def assert_bad(bstring):
(Pdb) a
bstring = ��

```

----------------------------------------
- Bitbucket: https://bitbucket.org/antocuni/pdb/issue/29

**Comment by blueyed** [comment]
This works for me using Python 3.7.2 and the following test file:
```python
def f(*args):
    __import__('pdb').set_trace()


f('\xff\xfe')
```

```
% python t-args.py
--Return--
[1] > /home/daniel/Vcs/pdbpp/t-args.py(2)f()->None
-> __import__('pdb').set_trace()
(Pdb++) args
('ÿþ',)
(Pdb++)
```

Using Python 2.7.15:
```
[1] > /home/daniel/Vcs/pdbpp/t-args.py(2)f()->None
-> __import__('pdb').set_trace()
(Pdb++) args
('\xff\xfe',)
(Pdb++)
```

(using pdbpp 654bcda)

@numerodix 
Is this still an issue for you?
What am I missing when trying to reproduce it?
