### ISSUE TITLE
KeyError: 'turquoise' in Pygments, via example pdbrc.py

### ISSUE THREAD

**Issue by choucavalier** [pdbpp/pdbpp#316]
`/tmp/test.py`:
```
import pdb
pdb.set_trace()
```
```
(base) viovene@valoup /tmp % python test.py
--Return--
[0] > /private/tmp/test.py(2)<module>()->None
-> pdb.set_trace()
> /private/tmp/test.py(2)

Traceback (most recent call last):
  File "test.py", line 2, in <module>
    pdb.set_trace()
  File "/Users/viovene/miniconda3/lib/python3.7/bdb.py", line 92, in trace_dispatch
    return self.dispatch_return(frame, arg)
  File "/Users/viovene/miniconda3/lib/python3.7/bdb.py", line 151, in dispatch_return
    self.user_return(frame, arg)
  File "/Users/viovene/miniconda3/lib/python3.7/pdb.py", line 293, in user_return
    self.interaction(frame, None)
  File "/Users/viovene/miniconda3/lib/python3.7/site-packages/pdb.py", line 231, in interaction
    self._cmdloop()
  File "/Users/viovene/miniconda3/lib/python3.7/pdb.py", line 321, in _cmdloop
    self.cmdloop()
  File "/Users/viovene/miniconda3/lib/python3.7/cmd.py", line 105, in cmdloop
    self.preloop()
  File "/Users/viovene/miniconda3/lib/python3.7/site-packages/pdb.py", line 902, in preloop
    self._print_if_sticky()
  File "/Users/viovene/miniconda3/lib/python3.7/site-packages/pdb.py", line 802, in _print_if_sticky
    self._printlonglist(sticky_range)
  File "/Users/viovene/miniconda3/lib/python3.7/site-packages/pdb.py", line 614, in _printlonglist
    self._print_lines_pdbpp(lines, lineno)
  File "/Users/viovene/miniconda3/lib/python3.7/site-packages/pdb.py", line 633, in _print_lines_pdbpp
    src = self.format_source('\n'.join(lines))
  File "/Users/viovene/miniconda3/lib/python3.7/site-packages/pdb.py", line 423, in format_source
    return highlight(src, self._lexer, self._fmt)
  File "/Users/viovene/miniconda3/lib/python3.7/site-packages/pygments/__init__.py", line 85, in highlight
    return format(lex(code, lexer), formatter, outfile)
  File "/Users/viovene/miniconda3/lib/python3.7/site-packages/pygments/__init__.py", line 64, in format
    formatter.format(tokens, realoutfile)
  File "/Users/viovene/miniconda3/lib/python3.7/site-packages/pygments/formatters/terminal.py", line 101, in format
    return Formatter.format(self, tokensource, outfile)
  File "/Users/viovene/miniconda3/lib/python3.7/site-packages/pygments/formatter.py", line 95, in format
    return self.format_unencoded(tokensource, outfile)
  File "/Users/viovene/miniconda3/lib/python3.7/site-packages/pygments/formatters/terminal.py", line 126, in format_unencoded
    outfile.write(ansiformat(color, line.rstrip('\n')))
  File "/Users/viovene/miniconda3/lib/python3.7/site-packages/pygments/console.py", line 68, in ansiformat
    result.append(codes[attr])
KeyError: 'turquoise'
```

`pip freeze`:
```
appdirs==1.4.3
asn1crypto==1.2.0
attrs==19.3.0
black==19.3b0
certifi==2019.9.11
cffi==1.13.0
chardet==3.0.4
Click==7.0
conda==4.7.12
conda-package-handling==1.6.0
cryptography==2.8
fancycompleter==0.8
greenlet==0.4.15
idna==2.8
jedi==0.15.1
joblib==0.14.0
llvmlite==0.30.0
msgpack==0.6.2
neovim==0.3.1
numba==0.46.0
numexpr==2.7.0
numpy==1.17.3
pandas==0.25.2
parso==0.5.1
pdbpp==0.10.2
pyaml==19.4.1
pycosat==0.6.3
pycparser==2.19
Pygments==2.4.2
pynvim==0.3.2
pyOpenSSL==19.0.0
PySocks==1.7.1
python-dateutil==2.8.0
pytz==2019.3
PyYAML==5.1.2
requests==2.22.0
ruamel-yaml==0.15.46
scikit-learn==0.21.3
scipy==1.3.1
six==1.12.0
tables==3.6.0
toml==0.10.0
tqdm==4.36.1
urllib3==1.24.2
wmctrl==0.3
```

**Comment by choucavalier** [comment]
Problem was in my `~/.pdbrc.py`

**Comment by fbicknel** [comment]
> Problem was in my `~/.pdbrc.py`

! well... what WAS the problem? :)

I replace this line: 
`terminal.Name.Namespace:     ('teal',        'turquoise'),`
with:
`terminal.Name.Namespace:     ('teal',        'white'),`
And things are better.

**Comment by blueyed** [comment]
Is this something that comes from the documentation?

Your (relevant part of) `~/.pdbrc.py` might be useful.

**Comment by fbicknel** [comment]
I had decided to use your [pdbrc.py file from the repo](https://github.com/pdbpp/pdbpp/blob/master/pdbrc.py).

The color turquoise was put there to keep us on our toes.  :)
![image](https://user-images.githubusercontent.com/1676056/74069349-eb1daa00-49cb-11ea-976e-7c3b258036c5.png)

**Comment by choucavalier** [comment]
@fbicknel sorry I should have mentioned the exact cause of the issue

**Comment by blueyed** [comment]
There is some comment/idea about how to proceed with the (apparently) broken config in https://github.com/pdbpp/pdbpp/pull/440#issuecomment-833905172.

**Comment by jugmac00** [comment]
When this gets fixed, please also move the configuration into the README, as a then 3rd example, cf https://github.com/pdbpp/pdbpp/pull/440#issuecomment-835263072
