### ISSUE TITLE
test_continue_arg_with_error raises UnicodeDecodeError on Windows

### ISSUE THREAD

**Issue by dougthor42** [pdbpp/pdbpp#341]
From discussion in #338 (https://github.com/pdbpp/pdbpp/pull/338#discussion_r348899768): When running tests on Windows, `test_continue_arg_with_error` fails with the below traceback.

It was decided to XFail the test and save it for later.

## TL;DR:

On Windows, py36:

+ v0.10.2: running the `continue` arg with something unexpected, eg: `c.foo`, exits the debugger
+ 6562a5a: running `c.foo` does **not** exit the debugger.
+ Unit tests on v0.10.2: `test_continue_arg_with_error` raises `UnicodeDecodeError`
+ Unit tests on 6562a5a: `test_continue_arg_with_error` raises `UnicodeDecodeError`

## Contents

+ [Version Info](#version-info)
+ [Steps to Reproduce](#steps-to-reproduce)
    + [v0.10.2](#v0-10-2)
    + [Commit 6562a5a](#6562a5a)
+ [Additional Discussion](#additional-discussion)
+ [Traceback](#traceback)

## Version Info

+ Python 3.6.3, 64-bit
+ 6562a5a and v0.10.2
+ OS: Windows 10 Pro 64bit, v1903

## Steps to Reproduce

1. Have a windows machine
2. Make a virtualenv: `python -m venv venv`
4. Activate that venv: `venv\Scripts\activate.bat`
5. Install tox: `python -m pip install tox==3.13.2`
6. Run tests: `tox -e py36 --force-dep="pytest @ git+https://github.com/blueyed/pytest@my-master" -- -k test_continue_arg_with_error`
7. See traceback (below)

## Investigation 

Something changed between v0.10.2 and 6562a5a:
+ v0.10.2: running `c.foo` exits the debugger
+ 6562a5a: running `c.foo` does *not* exit the debugger.

### v0.10.2

1. Have a windows machine
2. Make this file `foo.py`:
    ```python
    from pdb import set_trace
    def fn():
        set_trace()
        x = 1
        y = 2
        z = 3
        return x+y+z
    fn()
    ```
3. Make a virtualenv: `python -m venv venv`
4. Activate that venv: `venv\Scripts\activate.bat`
5. Install pdbpp: `python -m pip install pdbpp`
6. Run the file: `python foo.py`
7. At the pdbpp prompt, enter `c.foo`:
   ```
    (.venv) C:\dev_python\temp\foo>python foo.py
    [1] > [33;01mc:\dev_python\temp\foo\foo.py[00m([36;01m5[00m)fn()
    -> x = 1
    (Pdb++) c.foo
    *** The specified object '.foo' is not a function or was not found along sys.path.

    (.venv) C:\dev_python\temp\foo>
    ```

Notice that the debugger quits, and does so silently. (Ignore the color codes `[33;01m` - those will be supported in the future.)

## 6562a5a:

Using an sdist build from 6562a5a **does not have this issue**.

```
(.venv) C:\dev_python\temp\foo>python -m pip install "C:\dev_python\pdbpp\dist\pdbpp-0.10.3.dev143+g6562a5a.tar.gz"
... <lines removed for brevity> ...
Successfully installed pdbpp-0.10.3.dev143+g6562a5a
You are using pip version 9.0.1, however version 19.3.1 is available.
You should consider upgrading via the 'python -m pip install --upgrade pip' command.

(.venv) C:\dev_python\temp\foo>python foo.py
[1] > [33;01mc:\dev_python\temp\foo\foo.py[00m([36;01m5[00m)fn()
-> x = [94m1[39;49;00m
(Pdb++) c.bar
*** The specified object '.bar' is not a function or was not found along sys.path.
(Pdb++) c

(.venv) C:\dev_python\temp\foo>
```

## Additional discussion

These are the compiled notes from @blueyed and @dougthor42 in #338.

Running

```python
with open("testing/test_pdb.py") as fp:
    for lineno, line in enumerate(fp, start=1):
        print(lineno, repr(line))
```

results in:

```
2606 '2\n'
2607 '# c\n'
Traceback (most recent call last):
  File "<stdin>", line 2, in <module>
  File "C:\WinPython36_x64_zero\python-3.6.3.amd64\lib\encodings\cp1252.py", line 23, in decode
    return codecs.charmap_decode(input,self.errors,decoding_table)[0]
UnicodeDecodeError: 'charmap' codec can't decode byte 0x81 in position 6738: character maps to <undefined>
```

Using `iconv --from=cp1252 testing/test_pdb.py` chokes at:
 
https://github.com/pdbpp/pdbpp/blob/aabb10b07ac7db1aa5a503cddac9d08dbe58a087/testing/test_pdb.py#L3009

with the error:

```python
def test_utf8():
    def fn():
        # Ñ‚ÐµÑiconv: illegal input sequence at position 64082
```

Which we should protect against this issue (eg: not crashing), perhaps by wrapping
https://github.com/pdbpp/pdbpp/blob/8e19a9512ee9b0fc67d9170e73ac97816143894d/src/pdbpp.py#L1210
in a `try..except` block. From a quick glance however it appears to also be a bug in `pdb` itself in the first place.

## Traceback

```pytb
C:\WinPython36_x64_zero\python-3.6.3.amd64\Lib\pdb.py:648: in do_break
    lineno = int(arg)
E   ValueError: invalid literal for int() with base 10: '.foo'

During handling of the above exception, another exception occurred:
C:\WinPython36_x64_zero\python-3.6.3.amd64\Lib\pdb.py:659: in do_break
    code = func.__code__
E   AttributeError: 'str' object has no attribute '__code__'

During handling of the above exception, another exception occurred:
C:\dev_python\pdbpp\testing\test_pdb.py:3270: in test_continue_arg_with_error
    filename=RE_THIS_FILE_CANONICAL,
C:\dev_python\pdbpp\testing\test_pdb.py:277: in check
    expected, lines = run_func(func, expected)
C:\dev_python\pdbpp\testing\test_pdb.py:259: in run_func
    return expected, runpdb(func, commands)
C:\dev_python\pdbpp\testing\test_pdb.py:193: in runpdb
    func()
C:\dev_python\pdbpp\testing\test_pdb.py:3247: in fn
    x = 1
C:\dev_python\pdbpp\testing\test_pdb.py:3247: in fn
    x = 1
C:\WinPython36_x64_zero\python-3.6.3.amd64\Lib\bdb.py:48: in trace_dispatch
    return self.dispatch_line(frame)
C:\WinPython36_x64_zero\python-3.6.3.amd64\Lib\bdb.py:66: in dispatch_line
    self.user_line(frame)
C:\WinPython36_x64_zero\python-3.6.3.amd64\Lib\pdb.py:261: in user_line
    self.interaction(frame, None)
c:\dev_python\pdbpp\.tox\py36\lib\site-packages\pdbpp.py:381: in interaction
    return self._interaction(frame, traceback)
c:\dev_python\pdbpp\.tox\py36\lib\site-packages\pdbpp.py:409: in _interaction
    self._cmdloop()
C:\WinPython36_x64_zero\python-3.6.3.amd64\Lib\pdb.py:321: in _cmdloop
    self.cmdloop()
C:\WinPython36_x64_zero\python-3.6.3.amd64\Lib\cmd.py:138: in cmdloop
    stop = self.onecmd(line)
C:\WinPython36_x64_zero\python-3.6.3.amd64\Lib\pdb.py:418: in onecmd
    return cmd.Cmd.onecmd(self, line)
C:\WinPython36_x64_zero\python-3.6.3.amd64\Lib\cmd.py:217: in onecmd
    return func(arg)
c:\dev_python\pdbpp\.tox\py36\lib\site-packages\pdbpp.py:1210: in do_continue
    self.do_tbreak(arg)
C:\WinPython36_x64_zero\python-3.6.3.amd64\Lib\pdb.py:706: in do_tbreak
    self.do_break(arg, 1)
C:\WinPython36_x64_zero\python-3.6.3.amd64\Lib\pdb.py:667: in do_break
    (ok, filename, ln) = self.lineinfo(arg)
C:\WinPython36_x64_zero\python-3.6.3.amd64\Lib\pdb.py:740: in lineinfo
    answer = find_function(item, fname)
C:\WinPython36_x64_zero\python-3.6.3.amd64\Lib\pdb.py:100: in find_function
    for lineno, line in enumerate(fp, start=1):
c:\dev_python\pdbpp\.tox\py36\lib\encodings\cp1252.py:23: in decode
    return codecs.charmap_decode(input,self.errors,decoding_table)[0]
E   UnicodeDecodeError: 'charmap' codec can't decode byte 0x81 in position 6738: character maps to <undefined>
```

**Comment by blueyed** [comment]
Note that it stopped xfailing with Python 3.8.7: https://ci.appveyor.com/project/blueyed/pdbpp/builds/38526998:
```
C:\Python39\python.exe -m tox --force-dep="%PYTEST%"
GLOB sdist-make: C:\projects\pdbpp\setup.py
Using C:\projects\pdbpp\.tox\py38-coverage\Scripts\python.EXE (3.8.7 (tags/v3.8.7:6503f05, Dec 21 2020, 17:59:51) [MSC v.1928 64 bit (AMD64)]).
py38-coverage inst-nodeps: C:\projects\pdbpp\.tox\.tmp\package\1\pdbpp-0.10.3.dev227+gf412058.zip
py38-coverage installed: atomicwrites==1.4.0,attrs==20.3.0,colorama==0.4.4,coverage==5.5,fancycompleter @ git+https://github.com/pdbpp/fancycompleter@8ae963eff76b327b7533f39f40d04eb2b99fa3fd,funcsigs==1.0.2,more-itertools==8.7.0,packaging==20.9,pdbpp @ file:///C:/projects/pdbpp/.tox/.tmp/package/1/pdbpp-0.10.3.dev227%2Bgf412058.zip,pexpect==4.8.0,pluggy==0.13.1,ptyprocess==0.7.0,py==1.10.0,Pygments==2.8.1,pyparsing==2.4.7,pyreadline==2.1,pyrepl @ git+https://github.com/pdbpp/pyrepl@4d788a92bfcd20fb65005d3f7a78d6b65a7f180f,pytest @ git+https://github.com/blueyed/pytest@8eb380425395332ffdf2cd42b8d7cf8ffab2ea2e,pytest-cov==2.11.1,six==1.15.0,wcwidth==0.2.5,wmctrl==0.3
py38-coverage run-test-pre: PYTHONHASHSEED='325'
py38-coverage run-test: commands[0] | pytest
============================= test session starts =============================
platform win32 -- Python 3.8.7, pytest-5.2.3.dev1603+g8eb380425, py-1.10.0, pluggy-0.13.1 -- c:\projects\pdbpp\.tox\py38-coverage\scripts\python.exe
…
================================== FAILURES ===================================
________________________ test_continue_arg_with_error _________________________
[XPASS(strict)] Windows encoding issue. See comments and https://github.com/pdbpp/pdbpp/issues/341
---------------------------- Captured stdout call -----------------------------
\[ *[0-9]+\] > .*fn\(\)                                                                |  [36] > c:\projects\pdbpp\testing\test_pdb.py(3972)fn()
-> x = 1                                                                               |  -> x = 1
   5 frames hidden .*                                                                  |     5 frames hidden (try 'help hidden_frames')
# c.foo                                                                                |  # c.foo
\*\*\* The specified object '.foo' is not a function or was not found along sys.path.  |  *** The specified object '.foo' is not a function or was not found along sys.path.
# c 3974                                                                               |  # c 3974
Breakpoint  *[0-9]+ at c:\\projects\\pdbpp\\testing\\test_pdb\.py:3974                 |  Breakpoint 3 at c:\projects\pdbpp\testing\test_pdb.py:3974
Deleted breakpoint  *[0-9]+                                                            |  Deleted breakpoint 3 at c:\projects\pdbpp\testing\test_pdb.py:3974
\[ *[0-9]+\] > .*fn\(\)                                                                |  [36] > c:\projects\pdbpp\testing\test_pdb.py(3974)fn()
-> z = 3                                                                               |  -> z = 3
   5 frames hidden .*                                                                  |     5 frames hidden (try 'help hidden_frames')
# c                                                                                    |  # c
```

It still xfails on Python 3.6.8 (https://ci.appveyor.com/project/blueyed/pdbpp/builds/38527110) and 3.7.9 (https://ci.appveyor.com/project/blueyed/pdbpp/builds/38527138) now.
It also xfailed end of 2020 for Python 3.8.0: https://ci.appveyor.com/project/blueyed/pdbpp/builds/37052549/job/k86598o8359e97oy.

I'll assume this has been fixed in https://bugs.python.org/issue41894 for Python 3.10, and backported to 3.9.1 and 3.8.7.
