### ISSUE TITLE
Doesn’t install on OS X

### ISSUE THREAD

**Issue by antocuni** [pdbpp/pdbpp#37]
Originally reported by: **Hynek Schlawack (Bitbucket: [hynek](https://bitbucket.org/hynek), GitHub: [hynek](https://github.com/hynek))**

----------------------------------------

Hi,

0.8 seems to (indirectly) depend on funcsigs 0.2 which fails to install on OS X (it also pulls in distribute, good times).  funcsigs 0.4 installs fine.

```
$ pip wheel pdbpp
Collecting pdbpp
  Downloading https://pypi.vm.ag/root/pypi/+f/92e/1b8c947d8a8b9/pdbpp-0.8.tar.gz
Collecting fancycompleter>=0.2 (from pdbpp)
  Downloading https://pypi.vm.ag/root/pypi/+f/446/67c62c6db6318/fancycompleter-0.4.tar.gz
Collecting ordereddict (from pdbpp)
  Downloading https://pypi.vm.ag/root/pypi/+f/a0e/d854ee442051b/ordereddict-1.1.tar.gz
Collecting backports.inspect (from pdbpp)
  Downloading https://pypi.vm.ag/root/pypi/+f/17a/5042b2fdb6c2b/backports.inspect-0.0.2.tar.gz
Collecting wmctrl (from pdbpp)
  Downloading https://pypi.vm.ag/root/pypi/+f/3dd/c4ca04056627c/wmctrl-0.1.tar.gz
Collecting pygments (from pdbpp)
  File was already downloaded /Users/hynek/.wheels/Pygments-2.0.2-py3-none-any.whl
Collecting distribute (from backports.inspect->pdbpp)
  File was already downloaded /Users/hynek/.wheels/distribute-0.7.3-cp34-cp34m-macosx_10_9_x86_64.whl
Collecting funcsigs==0.2 (from backports.inspect->pdbpp)
  Downloading https://pypi.vm.ag/root/pypi/+f/1f5/6853306a9aa69/funcsigs-0.2.tar.gz (698kB)
    100% |################################| 700kB 6.5MB/s
    Downloading http://pypi.python.org/packages/source/d/distribute/distribute-0.6.34.tar.gz
    Extracting in /var/folders/n8/bvhdmjbn4ljc498jpsr3rq6r0000gn/T/tmpw8_cthqs
    Now working in /var/folders/n8/bvhdmjbn4ljc498jpsr3rq6r0000gn/T/tmpw8_cthqs/distribute-0.6.34
    Building a Distribute egg in /private/var/folders/n8/bvhdmjbn4ljc498jpsr3rq6r0000gn/T/pip-build-aby3evdm/funcsigs
    RefactoringTool: Skipping implicit fixer: buffer
    RefactoringTool: Skipping implicit fixer: idioms
    RefactoringTool: Skipping implicit fixer: set_literal
    RefactoringTool: Skipping implicit fixer: ws_comma
    RefactoringTool: Refactored build/src/tests/api_tests.txt
    RefactoringTool: Files that were modified:
    RefactoringTool: build/src/tests/api_tests.txt
    --- build/src/tests/api_tests.txt	(original)
    +++ build/src/tests/api_tests.txt	(refactored)
    @@ -39,7 +39,7 @@
         >>> dist.py_version == sys.version[:3]
         True
    -    >>> print dist.platform
    +    >>> print(dist.platform)
         None
     Including various computed attributes::
    @@ -199,7 +199,7 @@
     You can ask a WorkingSet to ``find()`` a distribution matching a requirement::
         >>> from pkg_resources import Requirement
    -    >>> print ws.find(Requirement.parse("Foo==1.0"))    # no match, return None
    +    >>> print(ws.find(Requirement.parse("Foo==1.0")))    # no match, return None
         None
         >>> ws.find(Requirement.parse("Bar==0.9"))  # match, return distribution
    @@ -211,7 +211,7 @@
         >>> try:
         ...     ws.find(Requirement.parse("Bar==1.0"))
         ... except VersionConflict:
    -    ...     print 'ok'
    +    ...     print('ok')
         ok
     You can subscribe a callback function to receive notifications whenever a new
    @@ -219,7 +219,7 @@
     once for each existing distribution in the working set, and then is called
     again for new distributions added thereafter::
    -    >>> def added(dist): print "Added", dist
    +    >>> def added(dist): print("Added", dist)
         >>> ws.subscribe(added)
         Added Bar 0.9
         >>> foo12 = Distribution(project_name="Foo", version="1.2", location="f12")
    Traceback (most recent call last):
      File "/private/var/folders/n8/bvhdmjbn4ljc498jpsr3rq6r0000gn/T/tmpw8_cthqs/distribute-0.6.34/build/src/pkg_resources.py", line 2463, in _dep_map
        return self.__dep_map
      File "/private/var/folders/n8/bvhdmjbn4ljc498jpsr3rq6r0000gn/T/tmpw8_cthqs/distribute-0.6.34/build/src/pkg_resources.py", line 2288, in __getattr__
        raise AttributeError(attr)
    AttributeError: _DistInfoDistribution__dep_map
    During handling of the above exception, another exception occurred:
    Traceback (most recent call last):
      File "setup.py", line 248, in <module>
        scripts = scripts,
      File "/Users/hynek/.pyenv/versions/3.4.2/lib/python3.4/distutils/core.py", line 108, in setup
        _setup_distribution = dist = klass(attrs)
      File "/private/var/folders/n8/bvhdmjbn4ljc498jpsr3rq6r0000gn/T/tmpw8_cthqs/distribute-0.6.34/build/src/setuptools/dist.py", line 225, in __init__
        _Distribution.__init__(self,attrs)
      File "/Users/hynek/.pyenv/versions/3.4.2/lib/python3.4/distutils/dist.py", line 280, in __init__
        self.finalize_options()
      File "/private/var/folders/n8/bvhdmjbn4ljc498jpsr3rq6r0000gn/T/tmpw8_cthqs/distribute-0.6.34/build/src/setuptools/dist.py", line 257, in finalize_options
        ep.require(installer=self.fetch_build_egg)
      File "/private/var/folders/n8/bvhdmjbn4ljc498jpsr3rq6r0000gn/T/tmpw8_cthqs/distribute-0.6.34/build/src/pkg_resources.py", line 2026, in require
        working_set.resolve(self.dist.requires(self.extras),env,installer)))
      File "/private/var/folders/n8/bvhdmjbn4ljc498jpsr3rq6r0000gn/T/tmpw8_cthqs/distribute-0.6.34/build/src/pkg_resources.py", line 2236, in requires
        dm = self._dep_map
      File "/private/var/folders/n8/bvhdmjbn4ljc498jpsr3rq6r0000gn/T/tmpw8_cthqs/distribute-0.6.34/build/src/pkg_resources.py", line 2465, in _dep_map
        self.__dep_map = self._compute_dependencies()
      File "/private/var/folders/n8/bvhdmjbn4ljc498jpsr3rq6r0000gn/T/tmpw8_cthqs/distribute-0.6.34/build/src/pkg_resources.py", line 2498, in _compute_dependencies
        common = frozenset(reqs_for_extra(None))
      File "/private/var/folders/n8/bvhdmjbn4ljc498jpsr3rq6r0000gn/T/tmpw8_cthqs/distribute-0.6.34/build/src/pkg_resources.py", line 2495, in reqs_for_extra
        if req.marker_fn(override={'extra':extra}):
      File "/private/var/folders/n8/bvhdmjbn4ljc498jpsr3rq6r0000gn/T/tmpw8_cthqs/distribute-0.6.34/build/src/_markerlib/markers.py", line 109, in marker_fn
        return eval(compiled_marker, environment)
      File "<environment marker>", line 1, in <module>
    NameError: name 'sys_platform' is not defined
    /private/var/folders/n8/bvhdmjbn4ljc498jpsr3rq6r0000gn/T/pip-build-aby3evdm/funcsigs/distribute-0.6.34-py3.4.egg
    Traceback (most recent call last):
      File "/private/var/folders/n8/bvhdmjbn4ljc498jpsr3rq6r0000gn/T/pip-build-aby3evdm/funcsigs/distribute_setup.py", line 150, in use_setuptools
        raise ImportError
    ImportError
    During handling of the above exception, another exception occurred:
    Traceback (most recent call last):
      File "<string>", line 20, in <module>
      File "/private/var/folders/n8/bvhdmjbn4ljc498jpsr3rq6r0000gn/T/pip-build-aby3evdm/funcsigs/setup.py", line 3, in <module>
        use_setuptools()
      File "/private/var/folders/n8/bvhdmjbn4ljc498jpsr3rq6r0000gn/T/pip-build-aby3evdm/funcsigs/distribute_setup.py", line 152, in use_setuptools
        return _do_download(version, download_base, to_dir, download_delay)
      File "/private/var/folders/n8/bvhdmjbn4ljc498jpsr3rq6r0000gn/T/pip-build-aby3evdm/funcsigs/distribute_setup.py", line 132, in _do_download
        _build_egg(egg, tarball, to_dir)
      File "/private/var/folders/n8/bvhdmjbn4ljc498jpsr3rq6r0000gn/T/pip-build-aby3evdm/funcsigs/distribute_setup.py", line 123, in _build_egg
        raise IOError('Could not build the egg.')
    OSError: Could not build the egg.
    Complete output from command python setup.py egg_info:
    Downloading http://pypi.python.org/packages/source/d/distribute/distribute-0.6.34.tar.gz

    Extracting in /var/folders/n8/bvhdmjbn4ljc498jpsr3rq6r0000gn/T/tmpw8_cthqs

    Now working in /var/folders/n8/bvhdmjbn4ljc498jpsr3rq6r0000gn/T/tmpw8_cthqs/distribute-0.6.34

    Building a Distribute egg in /private/var/folders/n8/bvhdmjbn4ljc498jpsr3rq6r0000gn/T/pip-build-aby3evdm/funcsigs

    creating build

    creating build/src

    creating build/src/_markerlib

    creating build/src/docs

    creating build/src/docs/_templates

    creating build/src/docs/_theme

    creating build/src/docs/_theme/nature

    creating build/src/docs/_theme/nature/static

    creating build/src/docs/build

    creating build/src/docs/build/html

    creating build/src/docs/build/html/_sources

    creating build/src/docs/build/html/_static

    creating build/src/setuptools

    creating build/src/setuptools/command

    creating build/src/setuptools/tests

    creating build/src/setuptools/tests/indexes

    creating build/src/setuptools/tests/indexes/test_links_priority

    creating build/src/setuptools/tests/indexes/test_links_priority/simple

    creating build/src/setuptools/tests/indexes/test_links_priority/simple/foobar

    creating build/src/tests

    creating build/src/tests/shlib_test

    copying setuptools/__init__.py -> build/src/setuptools

    copying setuptools/archive_util.py -> build/src/setuptools

    copying setuptools/depends.py -> build/src/setuptools

    copying setuptools/dist.py -> build/src/setuptools

    copying setuptools/extension.py -> build/src/setuptools

    copying setuptools/package_index.py -> build/src/setuptools

    copying setuptools/sandbox.py -> build/src/setuptools

    copying setuptools/script template (dev).py -> build/src/setuptools

    copying setuptools/script template.py -> build/src/setuptools

    copying setuptools/tests/__init__.py -> build/src/setuptools/tests

    copying setuptools/tests/doctest.py -> build/src/setuptools/tests

    copying setuptools/tests/py26compat.py -> build/src/setuptools/tests

    copying setuptools/tests/server.py -> build/src/setuptools/tests

    copying setuptools/tests/test_bdist_egg.py -> build/src/setuptools/tests

    copying setuptools/tests/test_build_ext.py -> build/src/setuptools/tests

    copying setuptools/tests/test_develop.py -> build/src/setuptools/tests

    copying setuptools/tests/test_dist_info.py -> build/src/setuptools/tests

    copying setuptools/tests/test_easy_install.py -> build/src/setuptools/tests

    copying setuptools/tests/test_markerlib.py -> build/src/setuptools/tests

    copying setuptools/tests/test_packageindex.py -> build/src/setuptools/tests

    copying setuptools/tests/test_resources.py -> build/src/setuptools/tests

    copying setuptools/tests/test_sandbox.py -> build/src/setuptools/tests

    copying setuptools/tests/test_sdist.py -> build/src/setuptools/tests

    copying setuptools/tests/test_test.py -> build/src/setuptools/tests

    copying setuptools/tests/test_upload_docs.py -> build/src/setuptools/tests

    copying setuptools/command/__init__.py -> build/src/setuptools/command

    copying setuptools/command/alias.py -> build/src/setuptools/command

    copying setuptools/command/bdist_egg.py -> build/src/setuptools/command

    copying setuptools/command/bdist_rpm.py -> build/src/setuptools/command

    copying setuptools/command/bdist_wininst.py -> build/src/setuptools/command

    copying setuptools/command/build_ext.py -> build/src/setuptools/command

    copying setuptools/command/build_py.py -> build/src/setuptools/command

    copying setuptools/command/develop.py -> build/src/setuptools/command

    copying setuptools/command/easy_install.py -> build/src/setuptools/command

    copying setuptools/command/egg_info.py -> build/src/setuptools/command

    copying setuptools/command/install.py -> build/src/setuptools/command

    copying setuptools/command/install_egg_info.py -> build/src/setuptools/command

    copying setuptools/command/install_lib.py -> build/src/setuptools/command

    copying setuptools/command/install_scripts.py -> build/src/setuptools/command

    copying setuptools/command/register.py -> build/src/setuptools/command

    copying setuptools/command/rotate.py -> build/src/setuptools/command

    copying setuptools/command/saveopts.py -> build/src/setuptools/command

    copying setuptools/command/sdist.py -> build/src/setuptools/command

    copying setuptools/command/setopt.py -> build/src/setuptools/command

    copying setuptools/command/test.py -> build/src/setuptools/command

    copying setuptools/command/upload.py -> build/src/setuptools/command

    copying setuptools/command/upload_docs.py -> build/src/setuptools/command

    copying setuptools/tests/win_script_wrapper.txt -> build/src/setuptools/tests

    copying setuptools/cli-32.exe -> build/src/setuptools

    copying setuptools/cli-64.exe -> build/src/setuptools

    copying setuptools/cli.exe -> build/src/setuptools

    copying setuptools/gui-32.exe -> build/src/setuptools

    copying setuptools/gui-64.exe -> build/src/setuptools

    copying setuptools/gui.exe -> build/src/setuptools

    copying tests/install_test.py -> build/src/tests

    copying tests/manual_test.py -> build/src/tests

    copying tests/test_distribute_setup.py -> build/src/tests

    copying tests/shlib_test/setup.py -> build/src/tests/shlib_test

    copying tests/shlib_test/test_hello.py -> build/src/tests/shlib_test

    copying tests/shlib_test/hello.c -> build/src/tests/shlib_test

    copying tests/shlib_test/hellolib.c -> build/src/tests/shlib_test

    copying tests/shlib_test/hello.pyx -> build/src/tests/shlib_test

    copying tests/api_tests.txt -> build/src/tests

    RefactoringTool: Skipping implicit fixer: buffer

    RefactoringTool: Skipping implicit fixer: idioms

    RefactoringTool: Skipping implicit fixer: set_literal

    RefactoringTool: Skipping implicit fixer: ws_comma

    RefactoringTool: Refactored build/src/tests/api_tests.txt

    RefactoringTool: Files that were modified:

    RefactoringTool: build/src/tests/api_tests.txt

    --- build/src/tests/api_tests.txt	(original)

    +++ build/src/tests/api_tests.txt	(refactored)

    @@ -39,7 +39,7 @@

         >>> dist.py_version == sys.version[:3]

         True



    -    >>> print dist.platform

    +    >>> print(dist.platform)

         None



     Including various computed attributes::

    @@ -199,7 +199,7 @@

     You can ask a WorkingSet to ``find()`` a distribution matching a requirement::



         >>> from pkg_resources import Requirement

    -    >>> print ws.find(Requirement.parse("Foo==1.0"))    # no match, return None

    +    >>> print(ws.find(Requirement.parse("Foo==1.0")))    # no match, return None

         None



         >>> ws.find(Requirement.parse("Bar==0.9"))  # match, return distribution

    @@ -211,7 +211,7 @@

         >>> try:

         ...     ws.find(Requirement.parse("Bar==1.0"))

         ... except VersionConflict:

    -    ...     print 'ok'

    +    ...     print('ok')

         ok



     You can subscribe a callback function to receive notifications whenever a new

    @@ -219,7 +219,7 @@

     once for each existing distribution in the working set, and then is called

     again for new distributions added thereafter::



    -    >>> def added(dist): print "Added", dist

    +    >>> def added(dist): print("Added", dist)

         >>> ws.subscribe(added)

         Added Bar 0.9

         >>> foo12 = Distribution(project_name="Foo", version="1.2", location="f12")

    copying setuptools/tests/indexes/test_links_priority/external.html -> build/src/setuptools/tests/indexes/test_links_priority

    copying setuptools/tests/indexes/test_links_priority/simple/foobar/index.html -> build/src/setuptools/tests/indexes/test_links_priority/simple/foobar

    copying docs/conf.py -> build/src/docs

    copying docs/easy_install.txt -> build/src/docs

    copying docs/index.txt -> build/src/docs

    copying docs/pkg_resources.txt -> build/src/docs

    copying docs/python3.txt -> build/src/docs

    copying docs/roadmap.txt -> build/src/docs

    copying docs/setuptools.txt -> build/src/docs

    copying docs/using.txt -> build/src/docs

    copying docs/build/html/_sources/easy_install.txt -> build/src/docs/build/html/_sources

    copying docs/build/html/_sources/index.txt -> build/src/docs/build/html/_sources

    copying docs/build/html/_sources/pkg_resources.txt -> build/src/docs/build/html/_sources

    copying docs/build/html/_sources/python3.txt -> build/src/docs/build/html/_sources

    copying docs/build/html/_sources/roadmap.txt -> build/src/docs/build/html/_sources

    copying docs/build/html/_sources/setuptools.txt -> build/src/docs/build/html/_sources

    copying docs/build/html/_sources/using.txt -> build/src/docs/build/html/_sources

    copying docs/_theme/nature/theme.conf -> build/src/docs/_theme/nature

    copying docs/build/html/_static/basic.css -> build/src/docs/build/html/_static

    copying docs/build/html/_static/nature.css -> build/src/docs/build/html/_static

    copying docs/build/html/_static/pygments.css -> build/src/docs/build/html/_static

    copying docs/_theme/nature/static/pygments.css -> build/src/docs/_theme/nature/static

    copying docs/_theme/nature/static/nature.css_t -> build/src/docs/_theme/nature/static

    copying docs/Makefile -> build/src/docs

    copying docs/_templates/indexsidebar.html -> build/src/docs/_templates

    copying _markerlib/__init__.py -> build/src/_markerlib

    copying _markerlib/markers.py -> build/src/_markerlib

    copying distribute_setup.py -> build/src

    copying easy_install.py -> build/src

    copying pkg_resources.py -> build/src

    copying release.py -> build/src

    copying setup.py -> build/src

    copying site.py -> build/src

    copying CHANGES.txt -> build/src

    copying CONTRIBUTORS.txt -> build/src

    copying DEVGUIDE.txt -> build/src

    copying README.txt -> build/src

    copying MANIFEST.in -> build/src

    copying launcher.c -> build/src

    Skipping implicit fixer: buffer

    Skipping implicit fixer: idioms

    Skipping implicit fixer: set_literal

    Skipping implicit fixer: ws_comma

    Traceback (most recent call last):

      File "/private/var/folders/n8/bvhdmjbn4ljc498jpsr3rq6r0000gn/T/tmpw8_cthqs/distribute-0.6.34/build/src/pkg_resources.py", line 2463, in _dep_map

        return self.__dep_map

      File "/private/var/folders/n8/bvhdmjbn4ljc498jpsr3rq6r0000gn/T/tmpw8_cthqs/distribute-0.6.34/build/src/pkg_resources.py", line 2288, in __getattr__

        raise AttributeError(attr)

    AttributeError: _DistInfoDistribution__dep_map



    During handling of the above exception, another exception occurred:



    Traceback (most recent call last):

      File "setup.py", line 248, in <module>

        scripts = scripts,

      File "/Users/hynek/.pyenv/versions/3.4.2/lib/python3.4/distutils/core.py", line 108, in setup

        _setup_distribution = dist = klass(attrs)

      File "/private/var/folders/n8/bvhdmjbn4ljc498jpsr3rq6r0000gn/T/tmpw8_cthqs/distribute-0.6.34/build/src/setuptools/dist.py", line 225, in __init__

        _Distribution.__init__(self,attrs)

      File "/Users/hynek/.pyenv/versions/3.4.2/lib/python3.4/distutils/dist.py", line 280, in __init__

        self.finalize_options()

      File "/private/var/folders/n8/bvhdmjbn4ljc498jpsr3rq6r0000gn/T/tmpw8_cthqs/distribute-0.6.34/build/src/setuptools/dist.py", line 257, in finalize_options

        ep.require(installer=self.fetch_build_egg)

      File "/private/var/folders/n8/bvhdmjbn4ljc498jpsr3rq6r0000gn/T/tmpw8_cthqs/distribute-0.6.34/build/src/pkg_resources.py", line 2026, in require

        working_set.resolve(self.dist.requires(self.extras),env,installer)))

      File "/private/var/folders/n8/bvhdmjbn4ljc498jpsr3rq6r0000gn/T/tmpw8_cthqs/distribute-0.6.34/build/src/pkg_resources.py", line 2236, in requires

        dm = self._dep_map

      File "/private/var/folders/n8/bvhdmjbn4ljc498jpsr3rq6r0000gn/T/tmpw8_cthqs/distribute-0.6.34/build/src/pkg_resources.py", line 2465, in _dep_map

        self.__dep_map = self._compute_dependencies()

      File "/private/var/folders/n8/bvhdmjbn4ljc498jpsr3rq6r0000gn/T/tmpw8_cthqs/distribute-0.6.34/build/src/pkg_resources.py", line 2498, in _compute_dependencies

        common = frozenset(reqs_for_extra(None))

      File "/private/var/folders/n8/bvhdmjbn4ljc498jpsr3rq6r0000gn/T/tmpw8_cthqs/distribute-0.6.34/build/src/pkg_resources.py", line 2495, in reqs_for_extra

        if req.marker_fn(override={'extra':extra}):

      File "/private/var/folders/n8/bvhdmjbn4ljc498jpsr3rq6r0000gn/T/tmpw8_cthqs/distribute-0.6.34/build/src/_markerlib/markers.py", line 109, in marker_fn

        return eval(compiled_marker, environment)

      File "<environment marker>", line 1, in <module>

    NameError: name 'sys_platform' is not defined

    /private/var/folders/n8/bvhdmjbn4ljc498jpsr3rq6r0000gn/T/pip-build-aby3evdm/funcsigs/distribute-0.6.34-py3.4.egg

    Traceback (most recent call last):

      File "/private/var/folders/n8/bvhdmjbn4ljc498jpsr3rq6r0000gn/T/pip-build-aby3evdm/funcsigs/distribute_setup.py", line 150, in use_setuptools

        raise ImportError

    ImportError



    During handling of the above exception, another exception occurred:



    Traceback (most recent call last):

      File "<string>", line 20, in <module>

      File "/private/var/folders/n8/bvhdmjbn4ljc498jpsr3rq6r0000gn/T/pip-build-aby3evdm/funcsigs/setup.py", line 3, in <module>

        use_setuptools()

      File "/private/var/folders/n8/bvhdmjbn4ljc498jpsr3rq6r0000gn/T/pip-build-aby3evdm/funcsigs/distribute_setup.py", line 152, in use_setuptools

        return _do_download(version, download_base, to_dir, download_delay)

      File "/private/var/folders/n8/bvhdmjbn4ljc498jpsr3rq6r0000gn/T/pip-build-aby3evdm/funcsigs/distribute_setup.py", line 132, in _do_download

        _build_egg(egg, tarball, to_dir)

      File "/private/var/folders/n8/bvhdmjbn4ljc498jpsr3rq6r0000gn/T/pip-build-aby3evdm/funcsigs/distribute_setup.py", line 123, in _build_egg

        raise IOError('Could not build the egg.')

    OSError: Could not build the egg.

    ----------------------------------------
```

----------------------------------------
- Bitbucket: https://bitbucket.org/antocuni/pdb/issue/37

**Comment by antocuni** [comment]
*Original comment by* **Antonio Cuni (Bitbucket: [antocuni](https://bitbucket.org/antocuni), GitHub: [antocuni](https://github.com/antocuni))**:

----------------------------------------

fwiw, as a temporary workaround: funcsigs is not strictly required, only to show the signature of callables when using the ?? command.
pdbpp works fine if it cannot import it

**Comment by antocuni** [comment]
*Original comment by* **Hynek Schlawack (Bitbucket: [hynek](https://bitbucket.org/hynek), GitHub: [hynek](https://github.com/hynek))**:

----------------------------------------

Could quickly you issue a 0.8.1 with the dep removed then?  I’m sure there’s more people trying to install 0.8 right now and running into that problem possibly dismissing the best python debugger because of it. .)

**Comment by antocuni** [comment]
*Original comment by* **Hynek Schlawack (Bitbucket: [hynek](https://bitbucket.org/hynek), GitHub: [hynek](https://github.com/hynek))**:

----------------------------------------

You guiseeeeee puhleazzzeeee! 😩

I really don't want to shadow pdbpp in our PyPI.

**Comment by antocuni** [comment]
*Original comment by* **Radu Voicilas (Bitbucket: [rvoicilas](https://bitbucket.org/rvoicilas), GitHub: [rvoicilas](https://github.com/rvoicilas))**:

----------------------------------------

fwiw, I had the exact same issue on Ubuntu while installing pdbpp with pip in a virtualenv. What worked for me was:

* clone the funcsigs 0.2 tag

* comment out line 2-3 from setup.py (where it imports from distribute_setup)

* python setup.py install for funcsigs

*  install pdbpp

As far as I can tell, the master for funcsigs has dropped the distribute dependency - would it be easy for pdbpp to upgrade to the latest funcsigs version ?

**Comment by antocuni** [comment]
*Original comment by* **Markus Zapke-Gründemann (Bitbucket: [keimlink](https://bitbucket.org/keimlink), GitHub: [keimlink](https://github.com/keimlink))**:

----------------------------------------

Same problem here on OS X 10.9.5 with Python 2.7.5.

**Comment by antocuni** [comment]
*Original comment by* **Marc Abramowitz (Bitbucket: [msabramo](https://bitbucket.org/msabramo), GitHub: [msabramo](https://github.com/msabramo))**:

----------------------------------------

@hynek and others: Please give https://bitbucket.org/antocuni/pdb/pull-request/35/use-funcsigs-package-instead-of/diff a look and see if it solves the problem, which is that `backports.inspect` depends on distribute.

**Comment by antocuni** [comment]
*Original comment by* **Marc Abramowitz (Bitbucket: [msabramo](https://bitbucket.org/msabramo), GitHub: [msabramo](https://github.com/msabramo))**:

----------------------------------------

Hmmm, unless funcsigs on PyPI also depends on distribute, in which case maybe I should make funcsigs a setuptools extra...?

**Comment by antocuni** [comment]
*Original comment by* **Marc Abramowitz (Bitbucket: [msabramo](https://bitbucket.org/msabramo), GitHub: [msabramo](https://github.com/msabramo))**:

----------------------------------------

AFAICT though, funcsigs doesn't depend on distribute:

```
$ mktmpenv
...

$ pip install funcsigs
Downloading/unpacking funcsigs
  Downloading funcsigs-0.4-py2.py3-none-any.whl
Installing collected packages: funcsigs
Successfully installed funcsigs
Cleaning up...

$ pip freeze
funcsigs==0.4
wsgiref==0.1.2
```

but `backports.inspect` does:

```
$ pip install backports.inspect
Downloading/unpacking backports.inspect
  Downloading backports.inspect-0.0.2.tar.gz
  Running setup.py (path:/Users/marca/python/virtualenvs/tmp-ffc8694a0d2f7048/build/backports.inspect/setup.py) egg_info for package backports.inspect

    no previously-included directories found matching 'dist'
Downloading/unpacking distribute (from backports.inspect)
  Downloading distribute-0.7.3.zip (145kB): 145kB downloaded
  Running setup.py (path:/Users/marca/python/virtualenvs/tmp-ffc8694a0d2f7048/build/distribute/setup.py) egg_info for package distribute

Downloading/unpacking funcsigs==0.2 (from backports.inspect)
  Downloading funcsigs-0.2.tar.gz (698kB): 698kB downloaded
  Running setup.py (path:/Users/marca/python/virtualenvs/tmp-ffc8694a0d2f7048/build/funcsigs/setup.py) egg_info for package funcsigs
    Downloading http://pypi.python.org/packages/source/d/distribute/distribute-0.6.34.tar.gz
    Extracting in /var/folders/gw/w0clrs515zx9x_55zgtpv4mm0000gp/T/tmpWS_4U3
    Now working in /var/folders/gw/w0clrs515zx9x_55zgtpv4mm0000gp/T/tmpWS_4U3/distribute-0.6.34
    Building a Distribute egg in /Users/marca/python/virtualenvs/tmp-ffc8694a0d2f7048/build/funcsigs
    /Users/marca/python/virtualenvs/tmp-ffc8694a0d2f7048/build/funcsigs/distribute-0.6.34-py2.7.egg

Requirement already satisfied (use --upgrade to upgrade): setuptools>=0.7 in /Users/marca/python/virtualenvs/tmp-ffc8694a0d2f7048/lib/python2.7/site-packages (from distribute->backports.inspect)
Installing collected packages: backports.inspect, funcsigs, distribute
  Running setup.py install for backports.inspect
    Skipping installation of /Users/marca/python/virtualenvs/tmp-ffc8694a0d2f7048/lib/python2.7/site-packages/backports/__init__.py (namespace package)

    no previously-included directories found matching 'dist'
    Installing /Users/marca/python/virtualenvs/tmp-ffc8694a0d2f7048/lib/python2.7/site-packages/backports.inspect-0.0.2-py2.7-nspkg.pth
  Found existing installation: funcsigs 0.4
    Uninstalling funcsigs:
      Successfully uninstalled funcsigs
  Running setup.py install for funcsigs

  Running setup.py install for distribute

Successfully installed backports.inspect funcsigs distribute
Cleaning up...
```

**Comment by antocuni** [comment]
*Original comment by* **Marc Abramowitz (Bitbucket: [msabramo](https://bitbucket.org/msabramo), GitHub: [msabramo](https://github.com/msabramo))**:

----------------------------------------

https://bitbucket.org/antocuni/pdb/pull-request/35/use-funcsigs-package-instead-of/diff merged.

**Comment by antocuni** [comment]
*Original comment by* **Marc Abramowitz (Bitbucket: [msabramo](https://bitbucket.org/msabramo), GitHub: [msabramo](https://github.com/msabramo))**:

----------------------------------------

OK, I pushed https://pypi.python.org/pypi/pdbpp/0.8.1 to PyPI. How does that look, folks?

**Comment by antocuni** [comment]
*Original comment by* **Hynek Schlawack (Bitbucket: [hynek](https://bitbucket.org/hynek), GitHub: [hynek](https://github.com/hynek))**:

----------------------------------------

WFM, but your version is confusingly set to 0.7: https://bitbucket.org/antocuni/pdb/src/1b12b2707837fa7495254f6d0e93ca908dd87915/pdb.py?at=default#cl-11 .  May I recommend something like https://github.com/hynek/structlog/blob/master/setup.py#L22 so you don’t have to remember to set the version in two places? :)

**Comment by antocuni** [comment]
*Original comment by* **Ronny Pfannschmidt (Bitbucket: [RonnyPfannschmidt](https://bitbucket.org/RonnyPfannschmidt), GitHub: [RonnyPfannschmidt](https://github.com/RonnyPfannschmidt))**:

----------------------------------------

fixed in 0.8.1

**Comment by antocuni** [comment]
*Original comment by* **Markus Zapke-Gründemann (Bitbucket: [keimlink](https://bitbucket.org/keimlink), GitHub: [keimlink](https://github.com/keimlink))**:

----------------------------------------

`pip install pdbpp` works now on OS X 10.9.5. Thanks for the quick fix!

**Comment by antocuni** [comment]
*Original comment by* **Marc Abramowitz (Bitbucket: [msabramo](https://bitbucket.org/msabramo), GitHub: [msabramo](https://github.com/msabramo))**:

----------------------------------------

Also, we're now using setuptools_scm for version number management. 

Everything working for you now, I hope, @hynek ?

**Comment by antocuni** [comment]
*Original comment by* **Hynek Schlawack (Bitbucket: [hynek](https://bitbucket.org/hynek), GitHub: [hynek](https://github.com/hynek))**:

----------------------------------------

Yep, that’s what I meant with WFM. :)  I just mentioned the version stuff because it confused me while checking.
