### ISSUE TITLE
install fails due to distribute dependencies of dependencies

### ISSUE THREAD

**Issue by antocuni** [pdbpp/pdbpp#40]
Originally reported by: **Ronny Pfannschmidt (Bitbucket: [RonnyPfannschmidt](https://bitbucket.org/RonnyPfannschmidt), GitHub: [RonnyPfannschmidt](https://github.com/RonnyPfannschmidt))**

----------------------------------------

```
$ pip install pdbpp
Collecting pdbpp
  Using cached pdbpp-0.8.tar.gz
Collecting fancycompleter>=0.2 (from pdbpp)
  Using cached fancycompleter-0.4.tar.gz
Collecting ordereddict (from pdbpp)
  Using cached ordereddict-1.1.tar.gz
Collecting backports.inspect (from pdbpp)
  Using cached backports.inspect-0.0.2.tar.gz
Collecting wmctrl (from pdbpp)
  Using cached wmctrl-0.1.tar.gz
Collecting pygments (from pdbpp)
  Using cached Pygments-2.0.2-py2-none-any.whl
Collecting pyrepl>=0.8.2 (from fancycompleter>=0.2->pdbpp)
  Using cached pyrepl-0.8.4.tar.gz
Collecting distribute (from backports.inspect->pdbpp)
  Using cached distribute-0.7.3.zip
Collecting funcsigs==0.2 (from backports.inspect->pdbpp)
  Using cached funcsigs-0.2.tar.gz
    Downloading http://pypi.python.org/packages/source/d/distribute/distribute-0.6.34.tar.gz
    Extracting in /tmp/tmp4u6w9x
    Now working in /tmp/tmp4u6w9x/distribute-0.6.34
    Building a Distribute egg in /tmp/pip-build-SEBsZn/funcsigs
    Traceback (most recent call last):
      File "setup.py", line 248, in <module>
        scripts = scripts,
      File "/usr/lib64/python2.7/distutils/core.py", line 111, in setup
        _setup_distribution = dist = klass(attrs)
      File "/tmp/tmp4u6w9x/distribute-0.6.34/setuptools/dist.py", line 225, in __init__
        _Distribution.__init__(self,attrs)
      File "/usr/lib64/python2.7/distutils/dist.py", line 287, in __init__
        self.finalize_options()
      File "/tmp/tmp4u6w9x/distribute-0.6.34/setuptools/dist.py", line 257, in finalize_options
        ep.require(installer=self.fetch_build_egg)
      File "/tmp/tmp4u6w9x/distribute-0.6.34/pkg_resources.py", line 2025, in require
        working_set.resolve(self.dist.requires(self.extras),env,installer))
      File "/tmp/tmp4u6w9x/distribute-0.6.34/pkg_resources.py", line 2235, in requires
        dm = self._dep_map
      File "/tmp/tmp4u6w9x/distribute-0.6.34/pkg_resources.py", line 2464, in _dep_map
        self.__dep_map = self._compute_dependencies()
      File "/tmp/tmp4u6w9x/distribute-0.6.34/pkg_resources.py", line 2497, in _compute_dependencies
        common = frozenset(reqs_for_extra(None))
      File "/tmp/tmp4u6w9x/distribute-0.6.34/pkg_resources.py", line 2494, in reqs_for_extra
        if req.marker_fn(override={'extra':extra}):
      File "/tmp/tmp4u6w9x/distribute-0.6.34/_markerlib/markers.py", line 109, in marker_fn
        return eval(compiled_marker, environment)
      File "<environment marker>", line 1, in <module>
    NameError: name 'sys_platform' is not defined
    /tmp/pip-build-SEBsZn/funcsigs/distribute-0.6.34-py2.7.egg
    Traceback (most recent call last):
      File "<string>", line 20, in <module>
      File "/tmp/pip-build-SEBsZn/funcsigs/setup.py", line 3, in <module>
        use_setuptools()
      File "distribute_setup.py", line 152, in use_setuptools
        return _do_download(version, download_base, to_dir, download_delay)
      File "distribute_setup.py", line 132, in _do_download
        _build_egg(egg, tarball, to_dir)
      File "distribute_setup.py", line 123, in _build_egg
        raise IOError('Could not build the egg.')
    IOError: Could not build the egg.
    Complete output from command python setup.py egg_info:
    Downloading http://pypi.python.org/packages/source/d/distribute/distribute-0.6.34.tar.gz
    
    Extracting in /tmp/tmp4u6w9x
    
    Now working in /tmp/tmp4u6w9x/distribute-0.6.34
    
    Building a Distribute egg in /tmp/pip-build-SEBsZn/funcsigs
    
    Traceback (most recent call last):
    
      File "setup.py", line 248, in <module>
    
        scripts = scripts,
    
      File "/usr/lib64/python2.7/distutils/core.py", line 111, in setup
    
        _setup_distribution = dist = klass(attrs)
    
      File "/tmp/tmp4u6w9x/distribute-0.6.34/setuptools/dist.py", line 225, in __init__
    
        _Distribution.__init__(self,attrs)
    
      File "/usr/lib64/python2.7/distutils/dist.py", line 287, in __init__
    
        self.finalize_options()
    
      File "/tmp/tmp4u6w9x/distribute-0.6.34/setuptools/dist.py", line 257, in finalize_options
    
        ep.require(installer=self.fetch_build_egg)
    
      File "/tmp/tmp4u6w9x/distribute-0.6.34/pkg_resources.py", line 2025, in require
    
        working_set.resolve(self.dist.requires(self.extras),env,installer))
    
      File "/tmp/tmp4u6w9x/distribute-0.6.34/pkg_resources.py", line 2235, in requires
    
        dm = self._dep_map
    
      File "/tmp/tmp4u6w9x/distribute-0.6.34/pkg_resources.py", line 2464, in _dep_map
    
        self.__dep_map = self._compute_dependencies()
    
      File "/tmp/tmp4u6w9x/distribute-0.6.34/pkg_resources.py", line 2497, in _compute_dependencies
    
        common = frozenset(reqs_for_extra(None))
    
      File "/tmp/tmp4u6w9x/distribute-0.6.34/pkg_resources.py", line 2494, in reqs_for_extra
    
        if req.marker_fn(override={'extra':extra}):
    
      File "/tmp/tmp4u6w9x/distribute-0.6.34/_markerlib/markers.py", line 109, in marker_fn
    
        return eval(compiled_marker, environment)
    
      File "<environment marker>", line 1, in <module>
    
    NameError: name 'sys_platform' is not defined
    
    /tmp/pip-build-SEBsZn/funcsigs/distribute-0.6.34-py2.7.egg
    
    Traceback (most recent call last):
    
      File "<string>", line 20, in <module>
    
      File "/tmp/pip-build-SEBsZn/funcsigs/setup.py", line 3, in <module>
    
        use_setuptools()
    
      File "distribute_setup.py", line 152, in use_setuptools
    
        return _do_download(version, download_base, to_dir, download_delay)
    
      File "distribute_setup.py", line 132, in _do_download
    
        _build_egg(egg, tarball, to_dir)
    
      File "distribute_setup.py", line 123, in _build_egg
    
        raise IOError('Could not build the egg.')
    
    IOError: Could not build the egg.
    
    ----------------------------------------
    Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-build-SEBsZn/funcsigs
```

----------------------------------------
- Bitbucket: https://bitbucket.org/antocuni/pdb/issue/40

**Comment by antocuni** [comment]
*Original comment by* **Ronny Pfannschmidt (Bitbucket: [RonnyPfannschmidt](https://bitbucket.org/RonnyPfannschmidt), GitHub: [RonnyPfannschmidt](https://github.com/RonnyPfannschmidt))**:

----------------------------------------

im on latest pip+setuptools
