### ISSUE TITLE
failure when embedding ipython

### ISSUE THREAD

**Issue by leej3** [pdbpp/pdbpp#400]
When using pdb or pdbpp the following usually works to enter an embedded ipython session:

```
from IPython import embed;embed()
```

This started failing for me recently when using pdbpp with the following software versions:
Software:
OS: Ubuntu 16
Python 3.6.9
IPython 7.14.0

<details>
<summary>Error message</summary>
<br>

```
*** AssertionError
Traceback (most recent call last):
  File "/opt/user_pip_packages/lib/python3.6/site-packages/IPython/terminal/embed.py", line 387, in embed
    frame.f_code.co_filename, frame.f_lineno), **kwargs)
  File "/opt/user_pip_packages/lib/python3.6/site-packages/traitlets/config/configurable.py", line 412, in instance
    inst = cls(*args, **kwargs)
  File "/opt/user_pip_packages/lib/python3.6/site-packages/IPython/terminal/embed.py", line 159, in __init__
    super(InteractiveShellEmbed,self).__init__(**kw)
  File "/opt/user_pip_packages/lib/python3.6/site-packages/IPython/terminal/interactiveshell.py", line 521, in __init__
    self.init_prompt_toolkit_cli()
  File "/opt/user_pip_packages/lib/python3.6/site-packages/IPython/terminal/interactiveshell.py", line 326, in init_prompt_toolkit_cli
    **self._extra_prompt_options())
  File "/opt/user_pip_packages/lib/python3.6/site-packages/prompt_toolkit/shortcuts/prompt.py", line 458, in __init__
    self.app = self._create_application(editing_mode, erase_when_done)
  File "/opt/user_pip_packages/lib/python3.6/site-packages/prompt_toolkit/shortcuts/prompt.py", line 738, in _create_application
    output=self._output,
  File "/opt/user_pip_packages/lib/python3.6/site-packages/prompt_toolkit/application/application.py", line 266, in __init__
    self.output = output or session.output
  File "/opt/user_pip_packages/lib/python3.6/site-packages/prompt_toolkit/application/current.py", line 65, in output
    self._output = create_output()
  File "/opt/user_pip_packages/lib/python3.6/site-packages/prompt_toolkit/output/defaults.py", line 62, in create_output
    return Vt100_Output.from_pty(stdout, term=get_term_environment_variable())
  File "/opt/user_pip_packages/lib/python3.6/site-packages/prompt_toolkit/output/vt100.py", line 473, in from_pty
    return cls(stdout, get_size, term=term)
  File "/opt/user_pip_packages/lib/python3.6/site-packages/prompt_toolkit/output/vt100.py", line 423, in __init__
    assert hasattr(stdout, "encoding")

```
</details>

I'm not sure what the stdout object is in this case. In pdbpp the sys.stdout is `<encodings.utf_8.StreamWriter object at 0x7f4ba287c390>` in my case

**Comment by kkirsche** [comment]
Is this command being executed once the breakpoint has been triggered or is this being called from the pdb run commands (pdbrc) file?

**Comment by leej3** [comment]
I think the former... The contents of the .pdbrc is `alias ipy from IPython import embed;embed()`. If I remember correctly the error is triggered when running that alias "ipy" (or running the command directly) during a debug session started by running `pytest --pdb path_to_arbitrary_file.py`. 

This was in the docker image afni/afni_cmake_build but I imagine it could be triggered in the smaller afni/afni_dev_base. I just tried in the most recent image and could not trigger the error for either pytest or using `python -m pdb path_to_arbitrary_file.py`.
