### ISSUE TITLE
_pdbpp_path_hack for wheel support doesn't work in Python 3

### ISSUE THREAD

**Issue by antocuni** [pdbpp/pdbpp#41]
Originally reported by: **Marc Abramowitz (Bitbucket: [msabramo](https://bitbucket.org/msabramo), GitHub: [msabramo](https://github.com/msabramo))**

----------------------------------------

```
Traceback (most recent call last):
  File "/Users/marca/dev/git-repos/pip/pip/basecommand.py", line 232, in main
    status = self.run(options, args)
  File "/Users/marca/dev/git-repos/pip/pip/commands/install.py", line 204, in run
    import pdb; pdb.set_trace()
  File "/Users/marca/dev/git-repos/django_ci_example/.tox/py34/lib/python3.4/site-packages/_pdbpp_path_hack/pdb.py", line 3, in <module>
    execfile(os.path.join(
NameError: name 'execfile' is not defined
```

----------------------------------------
- Bitbucket: https://bitbucket.org/antocuni/pdb/issue/41

**Comment by antocuni** [comment]
*Original comment by* **Marc Abramowitz (Bitbucket: [msabramo](https://bitbucket.org/msabramo), GitHub: [msabramo](https://github.com/msabramo))**:

----------------------------------------

Make __pdbpp_path_hack work with Python 3

by running `2to3 -w _pdbpp_path_hack/pdb.py`

fixes issue #41

**Comment by antocuni** [comment]
*Original comment by* **Marc Abramowitz (Bitbucket: [msabramo](https://bitbucket.org/msabramo), GitHub: [msabramo](https://github.com/msabramo))**:

----------------------------------------

@RonnyPfannschmidt: Please see https://bitbucket.org/antocuni/pdb/pull-request/41/make-__pdbpp_path_hack-work-with-python-3/diff

**Comment by antocuni** [comment]
*Original comment by* **Wouter Bolsterlee (Bitbucket: [wbolster](https://bitbucket.org/wbolster), GitHub: [wbolster](https://github.com/wbolster))**:

----------------------------------------

Can this please go in? Currently pdbpp is unusable with Python 3 after a "pip install pdbpp" using recent pip/setuptools in a virtualenv (which uses wheels by default).

**Comment by antocuni** [comment]
*Original comment by* **Daniel Hahler (Bitbucket: [blueyed](https://bitbucket.org/blueyed), GitHub: [blueyed](https://github.com/blueyed))**:

----------------------------------------

It appears to be merged, but a new PyPI release would be required.

**Comment by antocuni** [comment]
*Original comment by* **Marc Abramowitz (Bitbucket: [msabramo](https://bitbucket.org/msabramo), GitHub: [msabramo](https://github.com/msabramo))**:

----------------------------------------

Released https://pypi.python.org/pypi/pdbpp/0.8.3
