### ISSUE TITLE
Install problem on Windows 7, 32-Bit, with Python 2.7.6

### ISSUE THREAD

**Issue by antocuni** [pdbpp/pdbpp#43]
Originally reported by: **cappy2112 (Bitbucket: [tcappellini](https://bitbucket.org/tcappellini), GitHub: Unknown)**

----------------------------------------

While installing pdbpp on Windows 7.0 (32-Bit) with Python 2.7.6, 
this exception was displayed

C:\Users\SomeUser>pip install pdbpp
Downloading/unpacking pdbpp
  Downloading pdbpp-0.8.2.tar.gz (40Kb): 40Kb downloaded
  Running setup.py egg_info for package pdbpp
    zip_safe flag not set; analyzing archive contents...

    Installed c:\users\SomeUser\build\pdbpp\setuptools_scm-1.3.0-py2.7.egg
    your setuptools is too old (<12)
    setuptools_scm functionality is degraded

    package init file '_pdbpp_path_hack\__init__.py' not found (or not a regular file)
Downloading/unpacking fancycompleter>=0.2 (from pdbpp)
  Downloading fancycompleter-0.4.tar.gz
  Running setup.py egg_info for package fancycompleter

Requirement already satisfied (use --upgrade to upgrade): ordereddict in c:\python27\lib\site-packages (from pdbpp)
Downloading/unpacking wmctrl (from pdbpp)
  Downloading wmctrl-0.1.tar.gz
  Running setup.py egg_info for package wmctrl

Requirement already satisfied (use --upgrade to upgrade): pygments in c:\python27\lib\site-packages (from pdbpp)
Downloading/unpacking pyrepl>=0.8.2 (from fancycompleter>=0.2->pdbpp)
  Downloading pyrepl-0.8.4.tar.gz (45Kb): 45Kb downloaded
  Running setup.py egg_info for package pyrepl

Installing collected packages: fancycompleter, pdbpp, pyrepl, wmctrl
  Running setup.py install for fancycompleter

  Running setup.py install for pdbpp
    your setuptools is too old (<12)
    setuptools_scm functionality is degraded
    package init file '_pdbpp_path_hack\__init__.py' not found (or not a regular file)

    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "C:\Users\SomeUser\build\pdbpp\setup.py", line 70, in <module>
        'install_pth_hack': install_pth_hack,
      File "C:\Python27\lib\distutils\core.py", line 152, in setup
        dist.run_commands()
      File "C:\Python27\lib\distutils\dist.py", line 953, in run_commands
        self.run_command(cmd)
      File "C:\Python27\lib\distutils\dist.py", line 972, in run_command
        cmd_obj.run()
      File "build\bdist.win32\egg\setuptools\command\install.py", line 55, in run
      File "C:\Python27\lib\distutils\command\install.py", line 582, in run
        outputs = self.get_outputs()
      File "C:\Python27\lib\distutils\command\install.py", line 625, in get_outputs
        for filename in cmd.get_outputs():
      File "C:\Python27\lib\distutils\cmd.py", line 105, in __getattr__
        raise AttributeError, attr
    AttributeError: get_outputs
    Complete output from command C:\Python27\python.exe -c "import setuptools;__file__='C:\\Users\\SomeUser\\build\\pdbpp\\setup.py';execfile(__file__)" install --single-version-externally-managed --record c:\windows\temp\pip-g2zv5c-record\install-record.txt:
    your setuptools is too old (<12)

setuptools_scm functionality is degraded

running install

running build

running build_py

package init file '_pdbpp_path_hack\__init__.py' not found (or not a regular file)

creating build

creating build\lib

copying pdb.py -> build\lib

creating build\lib\_pdbpp_path_hack

copying _pdbpp_path_hack\pdb.py -> build\lib\_pdbpp_path_hack

running install_lib

copying build\lib\pdb.py -> C:\Python27\Lib\site-packages

creating C:\Python27\Lib\site-packages\_pdbpp_path_hack

copying build\lib\_pdbpp_path_hack\pdb.py -> C:\Python27\Lib\site-packages\_pdbpp_path_hack

byte-compiling C:\Python27\Lib\site-packages\pdb.py to pdb.pyc

byte-compiling C:\Python27\Lib\site-packages\_pdbpp_path_hack\pdb.py to pdb.pyc

running install_egg_info

running egg_info

writing requirements to pdbpp.egg-info\requires.txt

writing pdbpp.egg-info\PKG-INFO

writing top-level names to pdbpp.egg-info\top_level.txt

writing dependency_links to pdbpp.egg-info\dependency_links.txt

writing requirements to pdbpp.egg-info\requires.txt

writing pdbpp.egg-info\PKG-INFO

writing top-level names to pdbpp.egg-info\top_level.txt

writing dependency_links to pdbpp.egg-info\dependency_links.txt

warning: manifest_maker: standard file '-c' not found

reading manifest file 'pdbpp.egg-info\SOURCES.txt'

reading manifest template 'MANIFEST.in'

writing manifest file 'pdbpp.egg-info\SOURCES.txt'

Copying pdbpp.egg-info to C:\Python27\Lib\site-packages\pdbpp-0.8.2-py2.7.egg-info

running install_scripts

running install_pth_hack

Traceback (most recent call last):

  File "<string>", line 1, in <module>

  File "C:\Users\SomeUser\build\pdbpp\setup.py", line 70, in <module>

    'install_pth_hack': install_pth_hack,

  File "C:\Python27\lib\distutils\core.py", line 152, in setup

    dist.run_commands()

  File "C:\Python27\lib\distutils\dist.py", line 953, in run_commands

    self.run_command(cmd)

  File "C:\Python27\lib\distutils\dist.py", line 972, in run_command

    cmd_obj.run()

  File "build\bdist.win32\egg\setuptools\command\install.py", line 55, in run

  File "C:\Python27\lib\distutils\command\install.py", line 582, in run

    outputs = self.get_outputs()

  File "C:\Python27\lib\distutils\command\install.py", line 625, in get_outputs

    for filename in cmd.get_outputs():

  File "C:\Python27\lib\distutils\cmd.py", line 105, in __getattr__

    raise AttributeError, attr

AttributeError: get_outputs

----------------------------------------
Command C:\Python27\python.exe -c "import setuptools;__file__='C:\\Users\\SomeUser\\build\\pdbpp\\setup.py';execfile(__file__)" install --single-version-externally-managed --record c:\windows\temp\pip-g2zv5c-record\install-record.txt failed with error code 1
Storing complete log in C:\Users\SomeUser\AppData\Roaming\pip\pip.log

----------------------------------------
- Bitbucket: https://bitbucket.org/antocuni/pdb/issue/43

**Comment by antocuni** [comment]
*Original comment by* **Johannes Baiter (Bitbucket: [jbaiter](https://bitbucket.org/jbaiter), GitHub: [jbaiter](https://github.com/jbaiter))**:

----------------------------------------

I have a similar problem with Python 3.4 on Debian unstable, running pdb++ 0.8.2 from a virtual environment: http://www.pastebin.ca/2982252

**Comment by antocuni** [comment]
*Original comment by* **Leonardo Santagada (Bitbucket: [santagada](https://bitbucket.org/santagada), GitHub: [santagada](https://github.com/santagada))**:

----------------------------------------

More or less the same problem on Mac OS X and Python 3.4.3:

```
 running install_pth_hack
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/private/var/folders/ns/49hg_r812qx87cdr6kt106qm0000gn/T/pip-build-dla1i_ra/pdbpp/setup.py", line 70, in <module>
        'install_pth_hack': install_pth_hack,
      File "/usr/local/Cellar/python3/3.4.3/Frameworks/Python.framework/Versions/3.4/lib/python3.4/distutils/core.py", line 148, in setup
        dist.run_commands()
      File "/usr/local/Cellar/python3/3.4.3/Frameworks/Python.framework/Versions/3.4/lib/python3.4/distutils/dist.py", line 955, in run_commands
        self.run_command(cmd)
      File "/usr/local/Cellar/python3/3.4.3/Frameworks/Python.framework/Versions/3.4/lib/python3.4/distutils/dist.py", line 974, in run_command
        cmd_obj.run()
      File "/Users/santagada/.virtualenvs/soundcloud/lib/python3.4/site-packages/setuptools/command/install.py", line 61, in run
        return orig.install.run(self)
      File "/usr/local/Cellar/python3/3.4.3/Frameworks/Python.framework/Versions/3.4/lib/python3.4/distutils/command/install.py", line 558, in run
        outputs = self.get_outputs()
      File "/usr/local/Cellar/python3/3.4.3/Frameworks/Python.framework/Versions/3.4/lib/python3.4/distutils/command/install.py", line 600, in get_outputs
        for filename in cmd.get_outputs():
      File "/usr/local/Cellar/python3/3.4.3/Frameworks/Python.framework/Versions/3.4/lib/python3.4/distutils/cmd.py", line 103, in __getattr__
        raise AttributeError(attr)
    AttributeError: get_outputs

```

**Comment by antocuni** [comment]
*Original comment by* **Werner Beroux (Bitbucket: [wernight](https://bitbucket.org/wernight), GitHub: [wernight](https://github.com/wernight))**:

----------------------------------------

Simple way to reproduce on Linux (after installing Docker):


```
#!bash

$ docker run --rm python:3.4.3 pip install pdbpp==0.8.2
```

Also appears on Python 3.4.1. Install error doesn't appear on Python 3.3, however it shows a `NameError: name 'execfile' is not defined` during execution. On Python 2.7 everything seems to work.

Tried downgrading to `pip==1.5.6`, got the same error.

**Comment by blueyed** [comment]
Reproduced with 0.8.2, works with current: `docker run --rm python:3.4.3 pip install pdbpp`.
