### ISSUE TITLE
CI is broken

### ISSUE THREAD

**Issue by jugmac00** [pdbpp/pdbpp#441]
https://travis-ci.com/github/pdbpp/pdbpp/jobs/495675068

looks like we need to either pin `setuptools_scm` or drop support for Python < 3.6.

```
Processing ./.tox/.tmp/package/1/pdbpp-0.1.dev55+gea32b15.zip
    ERROR: Command errored out with exit status 1:
     command: /home/travis/build/pdbpp/pdbpp/.tox/py35-coverage/bin/python -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-req-build-zcghekfg/setup.py'"'"'; __file__='"'"'/tmp/pip-req-build-zcghekfg/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base pip-egg-info
         cwd: /tmp/pip-req-build-zcghekfg/
    Complete output (24 lines):
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-req-build-zcghekfg/setup.py", line 72, in <module>
        ["pdbpp_hijack_pdb.pth"],
      File "/home/travis/build/pdbpp/pdbpp/.tox/py35-coverage/lib/python3.5/site-packages/setuptools/__init__.py", line 145, in setup
        return distutils.core.setup(**attrs)
      File "/opt/python/3.5/lib/python3.5/distutils/core.py", line 108, in setup
        _setup_distribution = dist = klass(attrs)
      File "/home/travis/build/pdbpp/pdbpp/.tox/py35-coverage/lib/python3.5/site-packages/setuptools/dist.py", line 446, in __init__
        k: v for k, v in attrs.items()
      File "/opt/python/3.5/lib/python3.5/distutils/dist.py", line 281, in __init__
        self.finalize_options()
      File "/home/travis/build/pdbpp/pdbpp/.tox/py35-coverage/lib/python3.5/site-packages/setuptools/dist.py", line 734, in finalize_options
        ep.load()(self, ep.name, value)
      File "/home/travis/build/pdbpp/pdbpp/.tox/py35-coverage/lib/python3.5/site-packages/pkg_resources/__init__.py", line 2443, in load
        return self.resolve()
      File "/home/travis/build/pdbpp/pdbpp/.tox/py35-coverage/lib/python3.5/site-packages/pkg_resources/__init__.py", line 2449, in resolve
        module = __import__(self.module_name, fromlist=['__name__'], level=0)
      File "/tmp/pip-req-build-zcghekfg/.eggs/setuptools_scm-6.0.1-py3.5.egg/setuptools_scm/__init__.py", line 15, in <module>
        from .version import format_version, meta
      File "/tmp/pip-req-build-zcghekfg/.eggs/setuptools_scm-6.0.1-py3.5.egg/setuptools_scm/version.py", line 42
        trace(f"tag '{tag}' parsed to {result}")
                                              ^
    SyntaxError: invalid syntax
    ----------------------------------------
ERROR: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.
```

**Update**
`tox -e py35` passes on my local box :-/

Maybe that is related to installing a very old virtualenv version in travis.yml:
`python -m pip install --user virtualenv==16.7.3`

**Comment by blueyed** [comment]
Yeah, I've started to mess with it in https://github.com/pdbpp/pdbpp/pull/435 already.
(Note that it worked at end of 2020 still in https://github.com/pdbpp/pdbpp/pull/431).

**Comment by blueyed** [comment]
Made some progress in #435.
Needs some revisiting / cleanup - likely in the next days, or next weekend then.

**Comment by jugmac00** [comment]
This is great news! Thanks for all your work. I really love pdb++.

**Comment by blueyed** [comment]
Will move to GitHub Actions (#444).
