### ISSUE TITLE
Fails to install on OS X 10.10 python 3.4.3

### ISSUE THREAD

**Issue by antocuni** [pdbpp/pdbpp#45]
Originally reported by: **Adam Venturella (Bitbucket: [aventurella](https://bitbucket.org/aventurella), GitHub: [aventurella](https://github.com/aventurella))**

----------------------------------------

```
#!python

10:43 $ pip install pdbpp
Collecting pdbpp
  Using cached pdbpp-0.8.2.tar.gz
Requirement already satisfied (use --upgrade to upgrade): fancycompleter>=0.2 in /Users/username/.virtualenv/myproject/lib/python3.4/site-packages (from pdbpp)
Requirement already satisfied (use --upgrade to upgrade): ordereddict in /Users/username/.virtualenv/myproject/lib/python3.4/site-packages (from pdbpp)
Requirement already satisfied (use --upgrade to upgrade): wmctrl in /Users/username/.virtualenv/myproject/lib/python3.4/site-packages (from pdbpp)
Requirement already satisfied (use --upgrade to upgrade): pygments in /Users/username/.virtualenv/myproject/lib/python3.4/site-packages (from pdbpp)
Installing collected packages: pdbpp
  Running setup.py install for pdbpp
    Complete output from command /Users/username/.virtualenv/myproject/bin/python3.4 -c "import setuptools, tokenize;__file__='/private/var/folders/dd/fwnx0zzs0yxbp7wb1txdkzn00000gn/T/pip-build-_z6z8962/pdbpp/setup.py';exec(compile(getattr(tokenize, 'open', open)(__file__).read().replace('\r\n', '\n'), __file__, 'exec'))" install --record /var/folders/dd/fwnx0zzs0yxbp7wb1txdkzn00000gn/T/pip-p2wwjn0w-record/install-record.txt --single-version-externally-managed --compile --install-headers /Users/username/.virtualenv/myproject/bin/../include/site/python3.4/pdbpp:
    running install
    running build
    running build_py
    package init file '_pdbpp_path_hack/__init__.py' not found (or not a regular file)
    creating build
    creating build/lib
    copying pdb.py -> build/lib
    creating build/lib/_pdbpp_path_hack
    copying _pdbpp_path_hack/pdb.py -> build/lib/_pdbpp_path_hack
    running install_lib
    creating /Users/username/.virtualenv/myproject/lib/python3.4/site-packages/_pdbpp_path_hack
    copying build/lib/_pdbpp_path_hack/pdb.py -> /Users/username/.virtualenv/myproject/lib/python3.4/site-packages/_pdbpp_path_hack
    copying build/lib/pdb.py -> /Users/username/.virtualenv/myproject/lib/python3.4/site-packages
    byte-compiling /Users/username/.virtualenv/myproject/lib/python3.4/site-packages/_pdbpp_path_hack/pdb.py to pdb.cpython-34.pyc
    byte-compiling /Users/username/.virtualenv/myproject/lib/python3.4/site-packages/pdb.py to pdb.cpython-34.pyc
    running install_egg_info
    running egg_info
    writing dependency_links to pdbpp.egg-info/dependency_links.txt
    writing requirements to pdbpp.egg-info/requires.txt
    writing top-level names to pdbpp.egg-info/top_level.txt
    writing pdbpp.egg-info/PKG-INFO
    warning: manifest_maker: standard file '-c' not found

    reading manifest file 'pdbpp.egg-info/SOURCES.txt'
    reading manifest template 'MANIFEST.in'
    writing manifest file 'pdbpp.egg-info/SOURCES.txt'
    Copying pdbpp.egg-info to /Users/username/.virtualenv/myproject/lib/python3.4/site-packages/pdbpp-0.8.2-py3.4.egg-info
    running install_scripts
    running install_pth_hack
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/private/var/folders/dd/fwnx0zzs0yxbp7wb1txdkzn00000gn/T/pip-build-_z6z8962/pdbpp/setup.py", line 70, in <module>
        'install_pth_hack': install_pth_hack,
      File "/usr/local/Cellar/python3/3.4.3/Frameworks/Python.framework/Versions/3.4/lib/python3.4/distutils/core.py", line 148, in setup
        dist.run_commands()
      File "/usr/local/Cellar/python3/3.4.3/Frameworks/Python.framework/Versions/3.4/lib/python3.4/distutils/dist.py", line 955, in run_commands
        self.run_command(cmd)
      File "/usr/local/Cellar/python3/3.4.3/Frameworks/Python.framework/Versions/3.4/lib/python3.4/distutils/dist.py", line 974, in run_command
        cmd_obj.run()
      File "/Users/username/.virtualenv/myproject/lib/python3.4/site-packages/setuptools/command/install.py", line 61, in run
        return orig.install.run(self)
      File "/usr/local/Cellar/python3/3.4.3/Frameworks/Python.framework/Versions/3.4/lib/python3.4/distutils/command/install.py", line 558, in run
        outputs = self.get_outputs()
      File "/usr/local/Cellar/python3/3.4.3/Frameworks/Python.framework/Versions/3.4/lib/python3.4/distutils/command/install.py", line 600, in get_outputs
        for filename in cmd.get_outputs():
      File "/usr/local/Cellar/python3/3.4.3/Frameworks/Python.framework/Versions/3.4/lib/python3.4/distutils/cmd.py", line 103, in __getattr__
        raise AttributeError(attr)
    AttributeError: get_outputs

    ----------------------------------------
    Command "/Users/username/.virtualenv/myproject/bin/python3.4 -c "import setuptools, tokenize;__file__='/private/var/folders/dd/fwnx0zzs0yxbp7wb1txdkzn00000gn/T/pip-build-_z6z8962/pdbpp/setup.py';exec(compile(getattr(tokenize, 'open', open)(__file__).read().replace('\r\n', '\n'), __file__, 'exec'))" install --record /var/folders/dd/fwnx0zzs0yxbp7wb1txdkzn00000gn/T/pip-p2wwjn0w-record/install-record.txt --single-version-externally-managed --compile --install-headers /Users/username/.virtualenv/myproject/bin/../include/site/python3.4/pdbpp" failed with error code 1 in /private/var/folders/dd/fwnx0zzs0yxbp7wb1txdkzn00000gn/T/pip-build-_z6z8962/pdbpp
```

----------------------------------------
- Bitbucket: https://bitbucket.org/antocuni/pdb/issue/45

**Comment by antocuni** [comment]
*Original comment by* **Rene Muhl (Bitbucket: [ReneMuhl](https://bitbucket.org/ReneMuhl), GitHub: Unknown)**:

----------------------------------------

Same problem on Debian with Python3.4.2.


```
#!python

    reading manifest file 'pdbpp.egg-info/SOURCES.txt'
    reading manifest template 'MANIFEST.in'
    writing manifest file 'pdbpp.egg-info/SOURCES.txt'
    Copying pdbpp.egg-info to /home/rene/.virtualenvs/tmp-69aaba9f56783189/lib/python3.4/site-packages/pdbpp-0.8.2-py3.4.egg-info
    running install_scripts
    running install_pth_hack
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-build-inphuqr6/pdbpp/setup.py", line 70, in <module>
        'install_pth_hack': install_pth_hack,
      File "/usr/local/opt/python-3.4.2/lib/python3.4/distutils/core.py", line 148, in setup
        dist.run_commands()
      File "/usr/local/opt/python-3.4.2/lib/python3.4/distutils/dist.py", line 955, in run_commands
        self.run_command(cmd)
      File "/usr/local/opt/python-3.4.2/lib/python3.4/distutils/dist.py", line 974, in run_command
        cmd_obj.run()
      File "/home/rene/.virtualenvs/tmp-69aaba9f56783189/lib/python3.4/site-packages/setuptools/command/install.py", line 61, in run
        return orig.install.run(self)
      File "/usr/local/opt/python-3.4.2/lib/python3.4/distutils/command/install.py", line 558, in run
        outputs = self.get_outputs()
      File "/usr/local/opt/python-3.4.2/lib/python3.4/distutils/command/install.py", line 600, in get_outputs
        for filename in cmd.get_outputs():
      File "/usr/local/opt/python-3.4.2/lib/python3.4/distutils/cmd.py", line 103, in __getattr__
        raise AttributeError(attr)
    AttributeError: get_outputs
    
    ----------------------------------------
    Command "/home/rene/.virtualenvs/tmp-69aaba9f56783189/bin/python3.4 -c "import setuptools, tokenize;__file__='/tmp/pip-build-inphuqr6/pdbpp/setup.py';exec(compile(getattr(tokenize, 'open', open)(__file__).read().replace('\r\n', '\n'), __file__, 'exec'))" install --record /tmp/pip-m0oe5gxn-record/install-record.txt --single-version-externally-managed --compile --install-headers /home/rene/.virtualenvs/tmp-69aaba9f56783189/include/site/python3.4/pdbpp" failed with error code 1 in /tmp/pip-build-inphuqr6/pdbpp
```

<Update> It affects only version 0.8.2, I can install version 0.8.1.

**Comment by antocuni** [comment]
*Original comment by* **Adam Venturella (Bitbucket: [aventurella](https://bitbucket.org/aventurella), GitHub: [aventurella](https://github.com/aventurella))**:

----------------------------------------

Thanks for the 0.8.1 recommendation! This got me back into pdbpp as well. here's hoping for 0.8.3!

**Comment by antocuni** [comment]
*Original comment by* **Esteban Feldman (Bitbucket: [eka](https://bitbucket.org/eka), GitHub: [eka](https://github.com/eka))**:

----------------------------------------

Having the same problem with latest version.

**Comment by antocuni** [comment]
*Original comment by* **Adam Venturella (Bitbucket: [aventurella](https://bitbucket.org/aventurella), GitHub: [aventurella](https://github.com/aventurella))**:

----------------------------------------

Looks like this is also referenced here in #49

https://bitbucket.org/antocuni/pdb/issues/49/install-failure-on-python34-attributeerror

v0.8.1 still installs ok under python 3.5

**Comment by blueyed** [comment]
Closing as duplicate of #49.
