### ISSUE TITLE
pdbpp, pyrepl, pythoni and nvim checkhealth 

### ISSUE THREAD

**Issue by rachmadaniHaryono** [pdbpp/pdbpp#476]
### Subject of the issue
when installing pdbpp and run checkhealth on nvim it is shown that pdbpp will install pyrepl, which will install 2 additional python (`pythoni` and `pythoni1`) which are not compatible with python3

### Your environment
* ubuntu 21.10
* Python 3.9.7
* pdbpp 0.10.3

### Steps to reproduce
1. create empty project with `poetry init`
<details><summary>pyproject.toml</summary>
<p>

```shell
[tool.poetry]
name = "temp"
version = "0.1.0"
description = ""
authors = ["author <me@gmail.com>"]

[tool.poetry.dependencies]
python = "^3.9"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"

```
</p>
</details>

2. `poetry add pdbpp`

<details><summary>poetry add pdbpp</summary>
<p>

```shell
$ poetry add pdbpp
Using version ^0.10.3 for pdbpp

Updating dependencies
Resolving dependencies... (190.1s)

Writing lock file

Package operations: 5 installs, 0 updates, 7 removals

  • Removing click (8.0.3)
  • Removing flask (2.0.2)
  • Removing itsdangerous (2.0.1)
  • Removing jinja2 (3.0.3)
  • Removing markupsafe (2.0.1)
  • Removing werkzeug (2.0.2)
  • Removing wtforms (3.0.0)
  • Installing pyrepl (0.9.0)
  • Installing fancycompleter (0.9.1)
  • Installing pygments (2.10.0)
  • Installing wmctrl (0.4)
  • Installing pdbpp (0.10.3)
```

</p>
</details>

3. run `poetry run nvim -c checkhealth`

<details><summary>python virtualenv</summary>
<p>

```markdown
## Python virtualenv
  - WARNING: $VIRTUAL_ENV is set to: /home/r3r/.cache/pypoetry/virtualenvs/temp--3d1chu2-py3.9
    And its /bin directory contains: python, python3, python3.9, pythoni, pythoni1
    But $PATH yields this pythoni executable: Traceback (most recent call last):
    File "/home/r3r/.cache/pypoetry/virtualenvs/temp--3d1chu2-py3.9/bin/pythoni", line 30, in <module>
    from pyrepl.python_reader import main
    File "/home/r3r/.cache/pypoetry/virtualenvs/temp--3d1chu2-py3.9/lib/python3.9/site-packages/pyrepl/python_reader.py", line 25, in <module>
    from pyrepl.completing_reader import CompletingReader
    File "/home/r3r/.cache/pypoetry/virtualenvs/temp--3d1chu2-py3.9/lib/python3.9/site-packages/pyrepl/completing_reader.py", line 22, in <module>
    from pyrepl import commands, reader
    File "/home/r3r/.cache/pypoetry/virtualenvs/temp--3d1chu2-py3.9/lib/python3.9/site-packages/pyrepl/commands.py", line 376, in <module>
    from pyrepl import input
    File "/home/r3r/.cache/pypoetry/virtualenvs/temp--3d1chu2-py3.9/lib/python3.9/site-packages/pyrepl/input.py", line 39, in <module>
    from trace import trace
    ImportError: cannot import name 'trace' from 'trace' (/usr/lib/python3.9/trace.py)
    
    And $PATH in subshells yields this pythoni executable: Traceback (most recent call last):
    File "/home/r3r/.cache/pypoetry/virtualenvs/temp--3d1chu2-py3.9/bin/pythoni", line 30, in <module>
    from pyrepl.python_reader import main
    File "/home/r3r/.cache/pypoetry/virtualenvs/temp--3d1chu2-py3.9/lib/python3.9/site-packages/pyrepl/python_reader.py", line 25, in <module>
    from pyrepl.completing_reader import CompletingReader
    File "/home/r3r/.cache/pypoetry/virtualenvs/temp--3d1chu2-py3.9/lib/python3.9/site-packages/pyrepl/completing_reader.py", line 22, in <module>
    from pyrepl import commands, reader
    File "/home/r3r/.cache/pypoetry/virtualenvs/temp--3d1chu2-py3.9/lib/python3.9/site-packages/pyrepl/commands.py", line 376, in <module>
    from pyrepl import input
    File "/home/r3r/.cache/pypoetry/virtualenvs/temp--3d1chu2-py3.9/lib/python3.9/site-packages/pyrepl/input.py", line 39, in <module>
    from trace import trace
    ImportError: cannot import name 'trace' from 'trace' (/usr/lib/python3.9/trace.py)
    
    And $PATH yields this pythoni1 executable:   File "/home/r3r/.cache/pypoetry/virtualenvs/temp--3d1chu2-py3.9/bin/pythoni1", line 16
    print 'Python', sys.version
    ^
    SyntaxError: Missing parentheses in call to 'print'. Did you mean print('Python', sys.version)?
    
    And $PATH in subshells yields this pythoni1 executable:   File "/home/r3r/.cache/pypoetry/virtualenvs/temp--3d1chu2-py3.9/bin/pythoni1", line 16
    print 'Python', sys.version
    ^
    SyntaxError: Missing parentheses in call to 'print'. Did you mean print('Python', sys.version)?
    
    So invoking Python may lead to unexpected results.
    - ADVICE:
      - $PATH ambiguities arise if the virtualenv is not properly activated prior to launching Nvim. Close Nvim, activate the virtualenv, check that invoking Python from the command line launches the correct one, then relaunch Nvim.
      - $PATH ambiguities in subshells typically are caused by your shell config overriding the $PATH previously set by the virtualenv. Either prevent them from doing so, or use this workaround: https://vi.stackexchange.com/a/7654
```

</p>
</details>

4. run `pythoni` and `pythoni1`

<details><summary>pythoni1 and pythoni</summary>
<p>

```shell
$ poetry run pythoni
Traceback (most recent call last):
  File "/home/r3r/.cache/pypoetry/virtualenvs/temp--3d1chu2-py3.9/bin/pythoni", line 30, in <module>
    from pyrepl.python_reader import main
  File "/home/r3r/.cache/pypoetry/virtualenvs/temp--3d1chu2-py3.9/lib/python3.9/site-packages/pyrepl/python_reader.py", line 25, in <module>
    from pyrepl.completing_reader import CompletingReader
  File "/home/r3r/.cache/pypoetry/virtualenvs/temp--3d1chu2-py3.9/lib/python3.9/site-packages/pyrepl/completing_reader.py", line 22, in <module>
    from pyrepl import commands, reader
  File "/home/r3r/.cache/pypoetry/virtualenvs/temp--3d1chu2-py3.9/lib/python3.9/site-packages/pyrepl/commands.py", line 376, in <module>
    from pyrepl import input
  File "/home/r3r/.cache/pypoetry/virtualenvs/temp--3d1chu2-py3.9/lib/python3.9/site-packages/pyrepl/input.py", line 39, in <module>
    from trace import trace
ImportError: cannot import name 'trace' from 'trace' (/usr/lib/python3.9/trace.py)
$ poetry run pythoni1
  File "/home/r3r/.cache/pypoetry/virtualenvs/temp--3d1chu2-py3.9/bin/pythoni1", line 16
    print 'Python', sys.version
          ^
SyntaxError: Missing parentheses in call to 'print'. Did you mean print('Python', sys.version)?

```

</p>
</details>

### Expected behaviour

installing pdbpp should not add pythoni and pythoni1, which are not compatible with python 3

### Actual behaviour
pythoni and pythoni1 installed which are not compatible with python3
 
 ### Comment
 
 the title could be misleading and nvim may be considered not related to this issue at all. but this is the only way i actually found the pythoni and pythoni1
 
 there is also https://github.com/neovim/neovim/issues/13965 which may not detect pythoni and pythoni1 in future version of nvim
 
 this also could be considered pyrepl problem instead of pdbpp but i strongly recommend default pdbpp install to not include current pyrepl with current pythoni and pythoni1
 
 in the meantime i will try contribute to https://github.com/pypy/pyrepl so pythoni and pythoni1 is compatible with python3
 
 also as a note, i have read https://github.com/pdbpp/pdbpp/issues/260

**Comment by rachmadaniHaryono** [comment]
so i tried using latest github by running `poetry add git+https://github.com/pypy/pyrepl.git` but it also raise another error

```markdown
## Python virtualenv
  - WARNING: $VIRTUAL_ENV is set to: /home/r3r/.cache/pypoetry/virtualenvs/temp--3d1chu2-py3.9
    And its /bin directory contains: python, python3, python3.9, pythoni, pythoni1
    But $PATH yields this pythoni executable: Python 3.9.7 (default, Sep 10 2021, 14:59:43) 
    [GCC 11.2.0] on linux
    Type "help", "copyright", "credits" or "license" for more information.
    Traceback (most recent call last):
    File "/home/r3r/.cache/pypoetry/virtualenvs/temp--3d1chu2-py3.9/lib/python3.9/site-packages/pyrepl/reader.py", line 482, in prepare
    self.console.prepare()
    File "/home/r3r/.cache/pypoetry/virtualenvs/temp--3d1chu2-py3.9/lib/python3.9/site-packages/pyrepl/unix_console.py", line 357, in prepare
    self.__svtermstate = tcgetattr(self.input_fd)
    File "/home/r3r/.cache/pypoetry/virtualenvs/temp--3d1chu2-py3.9/lib/python3.9/site-packages/pyrepl/fancy_termios.py", line 34, in tcgetattr
    return TermState(termios.tcgetattr(fd))
    termios.error: (25, 'Inappropriate ioctl for device')
    
    During handling of the above exception, another exception occurred:
    
    Traceback (most recent call last):
    File "/home/r3r/.cache/pypoetry/virtualenvs/temp--3d1chu2-py3.9/bin/pythoni", line 36, in <module>
    main(use_pygame_console=('pg' in sys.argv))
    File "/home/r3r/.cache/pypoetry/virtualenvs/temp--3d1chu2-py3.9/lib/python3.9/site-packages/pyrepl/python_reader.py", line 403, in main
    getattr(rc, interactmethod)()
    File "/home/r3r/.cache/pypoetry/virtualenvs/temp--3d1chu2-py3.9/lib/python3.9/site-packages/pyrepl/python_reader.py", line 207, in interact
    l = unicode(self.reader.readline(), 'utf-8')
    File "/home/r3r/.cache/pypoetry/virtualenvs/temp--3d1chu2-py3.9/lib/python3.9/site-packages/pyrepl/reader.py", line 599, in readline
    self.prepare()
    File "/home/r3r/.cache/pypoetry/virtualenvs/temp--3d1chu2-py3.9/lib/python3.9/site-packages/pyrepl/historical_reader.py", line 240, in prepare
    super(HistoricalReader, self).prepare()
    File "/home/r3r/.cache/pypoetry/virtualenvs/temp--3d1chu2-py3.9/lib/python3.9/site-packages/pyrepl/reader.py", line 492, in prepare
    self.restore()
    File "/home/r3r/.cache/pypoetry/virtualenvs/temp--3d1chu2-py3.9/lib/python3.9/site-packages/pyrepl/reader.py", line 502, in restore
    self.console.restore()
    File "/home/r3r/.cache/pypoetry/virtualenvs/temp--3d1chu2-py3.9/lib/python3.9/site-packages/pyrepl/unix_console.py", line 389, in restore
    self.__maybe_write_code(self._rmkx)
    File "/home/r3r/.cache/pypoetry/virtualenvs/temp--3d1chu2-py3.9/lib/python3.9/site-packages/pyrepl/unix_console.py", line 305, in __maybe_write_code
    self.__write_code(fmt, *args)
    File "/home/r3r/.cache/pypoetry/virtualenvs/temp--3d1chu2-py3.9/lib/python3.9/site-packages/pyrepl/unix_console.py", line 301, in __write_code
    self.__buffer.append((curses.tparm(fmt, *args), 1))
    AttributeError: 'UnixConsole' object has no attribute '_UnixConsole__buffer'
    
    And $PATH in subshells yields this pythoni executable: Python 3.9.7 (default, Sep 10 2021, 14:59:43) 
    [GCC 11.2.0] on linux
    Type "help", "copyright", "credits" or "license" for more information.
    Traceback (most recent call last):
    File "/home/r3r/.cache/pypoetry/virtualenvs/temp--3d1chu2-py3.9/lib/python3.9/site-packages/pyrepl/reader.py", line 482, in prepare
    self.console.prepare()
    File "/home/r3r/.cache/pypoetry/virtualenvs/temp--3d1chu2-py3.9/lib/python3.9/site-packages/pyrepl/unix_console.py", line 357, in prepare
    self.__svtermstate = tcgetattr(self.input_fd)
    File "/home/r3r/.cache/pypoetry/virtualenvs/temp--3d1chu2-py3.9/lib/python3.9/site-packages/pyrepl/fancy_termios.py", line 34, in tcgetattr
    return TermState(termios.tcgetattr(fd))
    termios.error: (25, 'Inappropriate ioctl for device')
    
    During handling of the above exception, another exception occurred:
    
    Traceback (most recent call last):
    File "/home/r3r/.cache/pypoetry/virtualenvs/temp--3d1chu2-py3.9/bin/pythoni", line 36, in <module>
    main(use_pygame_console=('pg' in sys.argv))
    File "/home/r3r/.cache/pypoetry/virtualenvs/temp--3d1chu2-py3.9/lib/python3.9/site-packages/pyrepl/python_reader.py", line 403, in main
    getattr(rc, interactmethod)()
    File "/home/r3r/.cache/pypoetry/virtualenvs/temp--3d1chu2-py3.9/lib/python3.9/site-packages/pyrepl/python_reader.py", line 207, in interact
    l = unicode(self.reader.readline(), 'utf-8')
    File "/home/r3r/.cache/pypoetry/virtualenvs/temp--3d1chu2-py3.9/lib/python3.9/site-packages/pyrepl/reader.py", line 599, in readline
    self.prepare()
    File "/home/r3r/.cache/pypoetry/virtualenvs/temp--3d1chu2-py3.9/lib/python3.9/site-packages/pyrepl/historical_reader.py", line 240, in prepare
    super(HistoricalReader, self).prepare()
    File "/home/r3r/.cache/pypoetry/virtualenvs/temp--3d1chu2-py3.9/lib/python3.9/site-packages/pyrepl/reader.py", line 492, in prepare
    self.restore()
    File "/home/r3r/.cache/pypoetry/virtualenvs/temp--3d1chu2-py3.9/lib/python3.9/site-packages/pyrepl/reader.py", line 502, in restore
    self.console.restore()
    File "/home/r3r/.cache/pypoetry/virtualenvs/temp--3d1chu2-py3.9/lib/python3.9/site-packages/pyrepl/unix_console.py", line 389, in restore
    self.__maybe_write_code(self._rmkx)
    File "/home/r3r/.cache/pypoetry/virtualenvs/temp--3d1chu2-py3.9/lib/python3.9/site-packages/pyrepl/unix_console.py", line 305, in __maybe_write_code
    self.__write_code(fmt, *args)
    File "/home/r3r/.cache/pypoetry/virtualenvs/temp--3d1chu2-py3.9/lib/python3.9/site-packages/pyrepl/unix_console.py", line 301, in __write_code
    self.__buffer.append((curses.tparm(fmt, *args), 1))
    AttributeError: 'UnixConsole' object has no attribute '_UnixConsole__buffer'
    
    And $PATH yields this pythoni1 executable: Python 3.9.7 (default, Sep 10 2021, 14:59:43) 
    [GCC 11.2.0]
    Traceback (most recent call last):
    File "/home/r3r/.cache/pypoetry/virtualenvs/temp--3d1chu2-py3.9/lib/python3.9/site-packages/pyrepl/reader.py", line 482, in prepare
    self.console.prepare()
    File "/home/r3r/.cache/pypoetry/virtualenvs/temp--3d1chu2-py3.9/lib/python3.9/site-packages/pyrepl/unix_console.py", line 357, in prepare
    self.__svtermstate = tcgetattr(self.input_fd)
    File "/home/r3r/.cache/pypoetry/virtualenvs/temp--3d1chu2-py3.9/lib/python3.9/site-packages/pyrepl/fancy_termios.py", line 34, in tcgetattr
    return TermState(termios.tcgetattr(fd))
    termios.error: (25, 'Inappropriate ioctl for device')
    
    During handling of the above exception, another exception occurred:
    
    Traceback (most recent call last):
    File "/home/r3r/.cache/pypoetry/virtualenvs/temp--3d1chu2-py3.9/bin/pythoni1", line 19, in <module>
    run_multiline_interactive_console()
    File "/home/r3r/.cache/pypoetry/virtualenvs/temp--3d1chu2-py3.9/lib/python3.9/site-packages/pyrepl/simple_interact.py", line 64, in run_multiline_interactive_console
    statement = multiline_input(more_lines, ps1, ps2,
    File "/home/r3r/.cache/pypoetry/virtualenvs/temp--3d1chu2-py3.9/lib/python3.9/site-packages/pyrepl/readline.py", line 248, in multiline_input
    return reader.readline(returns_unicode=returns_unicode)
    File "/home/r3r/.cache/pypoetry/virtualenvs/temp--3d1chu2-py3.9/lib/python3.9/site-packages/pyrepl/reader.py", line 599, in readline
    self.prepare()
    File "/home/r3r/.cache/pypoetry/virtualenvs/temp--3d1chu2-py3.9/lib/python3.9/site-packages/pyrepl/historical_reader.py", line 240, in prepare
    super(HistoricalReader, self).prepare()
    File "/home/r3r/.cache/pypoetry/virtualenvs/temp--3d1chu2-py3.9/lib/python3.9/site-packages/pyrepl/reader.py", line 492, in prepare
    self.restore()
    File "/home/r3r/.cache/pypoetry/virtualenvs/temp--3d1chu2-py3.9/lib/python3.9/site-packages/pyrepl/reader.py", line 502, in restore
    self.console.restore()
    File "/home/r3r/.cache/pypoetry/virtualenvs/temp--3d1chu2-py3.9/lib/python3.9/site-packages/pyrepl/unix_console.py", line 389, in restore
    self.__maybe_write_code(self._rmkx)
    File "/home/r3r/.cache/pypoetry/virtualenvs/temp--3d1chu2-py3.9/lib/python3.9/site-packages/pyrepl/unix_console.py", line 305, in __maybe_write_code
    self.__write_code(fmt, *args)
    File "/home/r3r/.cache/pypoetry/virtualenvs/temp--3d1chu2-py3.9/lib/python3.9/site-packages/pyrepl/unix_console.py", line 301, in __write_code
    self.__buffer.append((curses.tparm(fmt, *args), 1))
    AttributeError: 'UnixConsole' object has no attribute '_UnixConsole__buffer'
    
    And $PATH in subshells yields this pythoni1 executable: Python 3.9.7 (default, Sep 10 2021, 14:59:43) 
    [GCC 11.2.0]
    Traceback (most recent call last):
    File "/home/r3r/.cache/pypoetry/virtualenvs/temp--3d1chu2-py3.9/lib/python3.9/site-packages/pyrepl/reader.py", line 482, in prepare
    self.console.prepare()
    File "/home/r3r/.cache/pypoetry/virtualenvs/temp--3d1chu2-py3.9/lib/python3.9/site-packages/pyrepl/unix_console.py", line 357, in prepare
    self.__svtermstate = tcgetattr(self.input_fd)
    File "/home/r3r/.cache/pypoetry/virtualenvs/temp--3d1chu2-py3.9/lib/python3.9/site-packages/pyrepl/fancy_termios.py", line 34, in tcgetattr
    return TermState(termios.tcgetattr(fd))
    termios.error: (25, 'Inappropriate ioctl for device')
    
    During handling of the above exception, another exception occurred:
    
    Traceback (most recent call last):
    File "/home/r3r/.cache/pypoetry/virtualenvs/temp--3d1chu2-py3.9/bin/pythoni1", line 19, in <module>
    run_multiline_interactive_console()
    File "/home/r3r/.cache/pypoetry/virtualenvs/temp--3d1chu2-py3.9/lib/python3.9/site-packages/pyrepl/simple_interact.py", line 64, in run_multiline_interactive_console
    statement = multiline_input(more_lines, ps1, ps2,
    File "/home/r3r/.cache/pypoetry/virtualenvs/temp--3d1chu2-py3.9/lib/python3.9/site-packages/pyrepl/readline.py", line 248, in multiline_input
    return reader.readline(returns_unicode=returns_unicode)
    File "/home/r3r/.cache/pypoetry/virtualenvs/temp--3d1chu2-py3.9/lib/python3.9/site-packages/pyrepl/reader.py", line 599, in readline
    self.prepare()
    File "/home/r3r/.cache/pypoetry/virtualenvs/temp--3d1chu2-py3.9/lib/python3.9/site-packages/pyrepl/historical_reader.py", line 240, in prepare
    super(HistoricalReader, self).prepare()
    File "/home/r3r/.cache/pypoetry/virtualenvs/temp--3d1chu2-py3.9/lib/python3.9/site-packages/pyrepl/reader.py", line 492, in prepare
    self.restore()
    File "/home/r3r/.cache/pypoetry/virtualenvs/temp--3d1chu2-py3.9/lib/python3.9/site-packages/pyrepl/reader.py", line 502, in restore
    self.console.restore()
    File "/home/r3r/.cache/pypoetry/virtualenvs/temp--3d1chu2-py3.9/lib/python3.9/site-packages/pyrepl/unix_console.py", line 389, in restore
    self.__maybe_write_code(self._rmkx)
    File "/home/r3r/.cache/pypoetry/virtualenvs/temp--3d1chu2-py3.9/lib/python3.9/site-packages/pyrepl/unix_console.py", line 305, in __maybe_write_code
    self.__write_code(fmt, *args)
    File "/home/r3r/.cache/pypoetry/virtualenvs/temp--3d1chu2-py3.9/lib/python3.9/site-packages/pyrepl/unix_console.py", line 301, in __write_code
    self.__buffer.append((curses.tparm(fmt, *args), 1))
    AttributeError: 'UnixConsole' object has no attribute '_UnixConsole__buffer'
    
    So invoking Python may lead to unexpected results.
    - ADVICE:
      - $PATH ambiguities arise if the virtualenv is not properly activated prior to launching Nvim. Close Nvim, activate the virtualenv, check that invoking Python from the command line launches the correct one, then relaunch Nvim.
      - $PATH ambiguities in subshells typically are caused by your shell config overriding the $PATH previously set by the virtualenv. Either prevent them from doing so, or use this workaround: https://vi.stackexchange.com/a/7654
```

but that mean this error is completely pyrepl issue and not pdbpp, so i will close this
