### ISSUE TITLE
Install failure on python3.4: AttributeError: get_outputs

### ISSUE THREAD

**Issue by antocuni** [pdbpp/pdbpp#49]
Originally reported by: **Ionel Maries Cristian (Bitbucket: [ionelmc](https://bitbucket.org/ionelmc), GitHub: [ionelmc](https://github.com/ionelmc))**

----------------------------------------

```
actionid: 3.4-pdbpp
msg: getenv
cmdargs: [local('/home/ionel/osp/python-remote-pdb/.env/3.4-pdbpp/bin/pip'), 'install', 'pytest', 'pytest-capturelog', 'pytest-cov', 'process-tests', 'pdbpp']
env: {'LESS': '-R', 'LC_CTYPE': 'en_US.UTF-8', 'SSH_CLIENT': '192.168.200.1 50604 22', 'LOGNAME': 'ionel', '_JAVA_OPTIONS': '-Dawt.useSystemAAFontSettings=on -Dswing.aatext=false', 'PATH': '/home/ionel/osp/python-remote-pdb/.env/3.4-pdbpp/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/home/ionel/bin:/home/ionel/.local/bin', 'HOME': '/home/ionel', 'PYTHONUNBUFFERED': 'yes', 'PS1': '%{\x1b[38;5;255m%}%{\x1b[48;5;241m%}(minibox)%{\x1b[48;5;15m%}%{\x1b[38;5;241m%}\xe2\x96\x8c%{\x1b[38;5;0m%}%{\x1b[48;5;15m%} ~ %{\x1b[48;5;237m%}%{\x1b[38;5;15m%}\xe2\xae\x80%{\x1b[38;5;250m%}%{\x1b[48;5;237m%} osp %{\x1b[48;5;237m%}%{\x1b[38;5;244m%}\xe2\xae\x81%{\x1b[38;5;250m%}%{\x1b[48;5;237m%} python-remote-pdb %{\x1b[48;5;94m%}%{\x1b[38;5;237m%}\xe2\xae\x80%{\x1b[38;5;15m%}%{\x1b[48;5;94m%} master 2\xea\x9c\x9b %{\x1b[48;5;34m%}%{\x1b[38;5;94m%}\xe2\xae\x80%{\x1b[38;5;0m%}%{\x1b[48;5;34m%}%{\x1b[0m%}%{\x1b[38;5;34m%}\xe2\xae\x80%{\x1b[0m%} ', 'DEBFULLNAME': 'Ionel Cristian Maries', 'DISPLAY': 'localhost:11.0', 'LANG': 'en_US.UTF-8', 'TERM': 'xterm', 'SHELL': '/bin/zsh', 'XDG_SESSION_COOKIE': 'f47816146d5573e8ff80304b000007ff-1434358180.951993-710393136', 'LANGUAGE': 'en_US:en', 'SHLVL': '1', 'ZSH': '/home/ionel/.antigen/repos/https-COLON--SLASH--SLASH-github.com-SLASH-robbyrussell-SLASH-oh-my-zsh.git', 'PYTHONHASHSEED': '64748888', 'EDITOR': 'nano', 'GREP_COLOR': '1;32', 'DEBEMAIL': 'contact@ionelmc.ro', 'PYTHONPATH': '/home/ionel/osp/python-remote-pdb/tests', 'SSH_AUTH_SOCK': '/tmp/ssh-bzMZN14188/agent.14188', 'VIRTUAL_ENV': '/home/ionel/osp/python-remote-pdb/.env/3.4-pdbpp', 'ADOTDIR': '/home/ionel/.antigen', 'LSCOLORS': 'Gxfxcxdxbxegedabagacad', 'ANTIGEN_DEFAULT_REPO_URL': 'https://github.com/robbyrussell/oh-my-zsh.git', '_': '/usr/local/bin/tox', 'GREP_OPTIONS': '--color=auto --exclude-dir=.cvs --exclude-dir=.git --exclude-dir=.hg --exclude-dir=.svn', 'SSH_TTY': '/dev/pts/1', 'OLDPWD': '/home/ionel/osp', 'PWD': '/home/ionel/osp/python-remote-pdb', 'DEFAULT_USER': 'ionel', 'MAIL': '/var/mail/ionel', 'SSH_CONNECTION': '192.168.200.1 50604 192.168.200.128 22', 'PAGER': 'less', 'USER': 'ionel'}

Collecting pytest
  Using cached pytest-2.7.1-py2.py3-none-any.whl
Collecting pytest-capturelog
Collecting pytest-cov
Collecting process-tests
  Using cached process_tests-0.8.0-py2.py3-none-any.whl
Collecting pdbpp
  Using cached pdbpp-0.8.2.tar.gz
Collecting py>=1.4.25 (from pytest)
  Using cached py-1.4.28-py2.py3-none-any.whl
Collecting cov-core>=1.14.0 (from pytest-cov)
Collecting coverage<4.0a1,>=3.7.1 (from pytest-cov)
Collecting fancycompleter>=0.2 (from pdbpp)
  Using cached fancycompleter-0.4.tar.gz
Collecting ordereddict (from pdbpp)
  Using cached ordereddict-1.1.tar.gz
Collecting wmctrl (from pdbpp)
  Using cached wmctrl-0.1.tar.gz
Collecting pygments (from pdbpp)
Installing collected packages: py, pytest, pytest-capturelog, coverage, cov-core, pytest-cov, process-tests, fancycompleter, ordereddict, wmctrl, pygments, pdbpp
  Running setup.py install for fancycompleter
  Running setup.py install for ordereddict
  Running setup.py install for wmctrl
  Running setup.py install for pdbpp
    Complete output from command /home/ionel/osp/python-remote-pdb/.env/3.4-pdbpp/bin/python -c "import setuptools, tokenize;__file__='/tmp/pip-build-l2skk89n/pdbpp/setup.py';exec(compile(getattr(tokenize, 'open', open)(__file__).read().replace('\r\n', '\n'), __file__, 'exec'))" install --record /tmp/pip-b1_v23_m-record/install-record.txt --single-version-externally-managed --compile --install-headers /home/ionel/osp/python-remote-pdb/.env/3.4-pdbpp/include/site/python3.4/pdbpp:
    running install
    running build
    running build_py
    package init file '_pdbpp_path_hack/__init__.py' not found (or not a regular file)
    creating build
    creating build/lib
    copying pdb.py -> build/lib
    creating build/lib/_pdbpp_path_hack
    copying _pdbpp_path_hack/pdb.py -> build/lib/_pdbpp_path_hack
    running install_lib
    creating /home/ionel/osp/python-remote-pdb/.env/3.4-pdbpp/lib/python3.4/site-packages/_pdbpp_path_hack
    copying build/lib/_pdbpp_path_hack/pdb.py -> /home/ionel/osp/python-remote-pdb/.env/3.4-pdbpp/lib/python3.4/site-packages/_pdbpp_path_hack
    copying build/lib/pdb.py -> /home/ionel/osp/python-remote-pdb/.env/3.4-pdbpp/lib/python3.4/site-packages
    byte-compiling /home/ionel/osp/python-remote-pdb/.env/3.4-pdbpp/lib/python3.4/site-packages/_pdbpp_path_hack/pdb.py to pdb.cpython-34.pyc
    byte-compiling /home/ionel/osp/python-remote-pdb/.env/3.4-pdbpp/lib/python3.4/site-packages/pdb.py to pdb.cpython-34.pyc
    running install_egg_info
    running egg_info
    writing top-level names to pdbpp.egg-info/top_level.txt
    writing requirements to pdbpp.egg-info/requires.txt
    writing pdbpp.egg-info/PKG-INFO
    writing dependency_links to pdbpp.egg-info/dependency_links.txt
    warning: manifest_maker: standard file '-c' not found
    
    reading manifest file 'pdbpp.egg-info/SOURCES.txt'
    reading manifest template 'MANIFEST.in'
    writing manifest file 'pdbpp.egg-info/SOURCES.txt'
    Copying pdbpp.egg-info to /home/ionel/osp/python-remote-pdb/.env/3.4-pdbpp/lib/python3.4/site-packages/pdbpp-0.8.2-py3.4.egg-info
    running install_scripts
    running install_pth_hack
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-build-l2skk89n/pdbpp/setup.py", line 70, in <module>
        'install_pth_hack': install_pth_hack,
      File "/usr/lib/python3.4/distutils/core.py", line 148, in setup
        dist.run_commands()
      File "/usr/lib/python3.4/distutils/dist.py", line 955, in run_commands
        self.run_command(cmd)
      File "/usr/lib/python3.4/distutils/dist.py", line 974, in run_command
        cmd_obj.run()
      File "/home/ionel/osp/python-remote-pdb/.env/3.4-pdbpp/lib/python3.4/site-packages/setuptools/command/install.py", line 61, in run
        return orig.install.run(self)
      File "/usr/lib/python3.4/distutils/command/install.py", line 601, in run
        outputs = self.get_outputs()
      File "/usr/lib/python3.4/distutils/command/install.py", line 643, in get_outputs
        for filename in cmd.get_outputs():
      File "/usr/lib/python3.4/distutils/cmd.py", line 103, in __getattr__
        raise AttributeError(attr)
    AttributeError: get_outputs
    
    ----------------------------------------
Command "/home/ionel/osp/python-remote-pdb/.env/3.4-pdbpp/bin/python -c "import setuptools, tokenize;__file__='/tmp/pip-build-l2skk89n/pdbpp/setup.py';exec(compile(getattr(tokenize, 'open', open)(__file__).read().replace('\r\n', '\n'), __file__, 'exec'))" install --record /tmp/pip-b1_v23_m-record/install-record.txt --single-version-externally-managed --compile --install-headers /home/ionel/osp/python-remote-pdb/.env/3.4-pdbpp/include/site/python3.4/pdbpp" failed with error code 1 in /tmp/pip-build-l2skk89n/pdbpp
```

----------------------------------------
- Bitbucket: https://bitbucket.org/antocuni/pdb/issue/49

**Comment by antocuni** [comment]
*Original comment by* **Ionel Maries Cristian (Bitbucket: [ionelmc](https://bitbucket.org/ionelmc), GitHub: [ionelmc](https://github.com/ionelmc))**:

----------------------------------------

Here's an example of portable way to install pth files: https://github.com/ionelmc/python-manhole/blob/master/setup.py

I'd make a PR but I don't have the time right now.

**Comment by antocuni** [comment]
*Original comment by* **Adam Venturella (Bitbucket: [aventurella](https://bitbucket.org/aventurella), GitHub: [aventurella](https://github.com/aventurella))**:

----------------------------------------

I've got the same issue. Just tried installing the tip, still fails there:

```
pip install https://bitbucket.org/antocuni/pdb/get/tip.zip#egg=pdbpp-0.8.3
```


```
running install_pth_hack
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-build-w3ltbjhh/pdbpp/setup.py", line 79, in <module>
        'install_pth_hack': install_pth_hack,
      File "/usr/local/lib/python3.5/distutils/core.py", line 148, in setup
        dist.run_commands()
      File "/usr/local/lib/python3.5/distutils/dist.py", line 955, in run_commands
        self.run_command(cmd)
      File "/usr/local/lib/python3.5/distutils/dist.py", line 974, in run_command
        cmd_obj.run()
      File "/usr/local/lib/python3.5/site-packages/setuptools/command/install.py", line 61, in run
        return orig.install.run(self)
      File "/usr/local/lib/python3.5/distutils/command/install.py", line 558, in run
        outputs = self.get_outputs()
      File "/usr/local/lib/python3.5/distutils/command/install.py", line 600, in get_outputs
        for filename in cmd.get_outputs():
      File "/usr/local/lib/python3.5/distutils/cmd.py", line 103, in __getattr__
        raise AttributeError(attr)
    AttributeError: get_outputs

    ----------------------------------------
Command "/usr/local/bin/python3.5 -u -c "import setuptools, tokenize;__file__='/tmp/pip-build-w3ltbjhh/pdbpp/setup.py';exec(compile(getattr(tokenize, 'open', open)(__file__).read().replace('\r\n', '\n'), __file__, 'exec'))" install --record /tmp/pip-noou27tu-record/install-record.txt --single-version-externally-managed --compile" failed with error code 1 in /tmp
/pip-build-w3ltbjhh/pdbpp/
```

**Comment by antocuni** [comment]
*Original comment by* **Uwe Schmitt (Bitbucket: [uweschmitt](https://bitbucket.org/uweschmitt), GitHub: [uweschmitt](https://github.com/uweschmitt))**:

----------------------------------------

Same with Python 3.5.

**Comment by antocuni** [comment]
*Original comment by* **Mikko Ohtamaa (Bitbucket: [miohtama](https://bitbucket.org/miohtama), GitHub: [miohtama](https://github.com/miohtama))**:

----------------------------------------

I am not vell wersed in deep disutils magic to understand what this issue is all about. However as a workaround one can do:

       easy_install pdbpp

**Comment by antocuni** [comment]
*Original comment by* **Adam Venturella (Bitbucket: [aventurella](https://bitbucket.org/aventurella), GitHub: [aventurella](https://github.com/aventurella))**:

----------------------------------------

@miohtama Thanks! this works!

**Comment by antocuni** [comment]
*Original comment by* **Daniel Hahler (Bitbucket: [blueyed](https://bitbucket.org/blueyed), GitHub: [blueyed](https://github.com/blueyed))**:

----------------------------------------

I've only noticed this when installing it in Docker, which it does not appear to be a problem on the host itself.

The workaround with using `easy_install` works there, too.

Is it related to stdout/stdin not being connected (or in a different way) maybe, e.g. with tox and Docker?!

**Comment by antocuni** [comment]
*Original comment by* **Dima Tisnek (Bitbucket: [dimaqq](https://bitbucket.org/dimaqq), GitHub: [dimaqq](https://github.com/dimaqq))**:

----------------------------------------

Ping! Any update? I see this is not the only only package in the world that got bitten so.

Certainly we can do better than "fall back to easy install" for the version at pypi's recommended version.

**Comment by keimlink** [comment]
Seems this issue has been solved. Successfully installed pdbpp 0.9.2 into a Docker container.

**Comment by blueyed** [comment]
Thanks for the update.
Likely fixed in distutils or some dependency I guess..
