### ISSUE TITLE
doesn't work without fancycompleter

### ISSUE THREAD

**Issue by antocuni** [pdbpp/pdbpp#5]
Originally reported by: **Anonymous**

----------------------------------------

pdb.py unconditionally imports fancycompleter, which is not part of the standard python library. It really should gracefully handle the case where it's not installed.

tnewsome@nelson20:~/ar1/src$ python
Python 2.6.2 (r262:71600, Jun  4 2010, 18:28:58) 
[GCC 4.4.3 20100127 (Red Hat 4.4.3-4)] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> import pdb
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/tnewsome/python/pdb.py", line 21, in <module>
    from fancycompleter import Completer, ConfigurableClass, Color
ImportError: No module named fancycompleter
>>> 

----------------------------------------
- Bitbucket: https://bitbucket.org/antocuni/pdb/issue/5

**Comment by antocuni** [comment]
*Original comment by* **Antonio Cuni (Bitbucket: [antocuni](https://bitbucket.org/antocuni), GitHub: [antocuni](https://github.com/antocuni))**:

----------------------------------------

Unfortunately, it's not so easy to remove the dependency on it: apart from TAB completion, pdb++ uses fancycompleter also for handling the configuration file (~/.pdbrc.py).
Actually, pdb++ and fancycompleter were born together, then I split them in two packages because the latter is useful also at the python prompt.

The alternative would be to move the ConfigurableClass to its own package, and have both to depend on it: however, I'm not sure it's an improvement, because you would still need to install a dependency in order to use it.
