### ISSUE TITLE
An error occurs when exiting (BdbQuit)

### ISSUE THREAD

**Issue by brucmao** [pdbpp/pdbpp#506]
I update pyreadline to pyreadline3 with following command

`pip install --upgrade https://github.com/pyreadline3/pyreadline3/tarball/master`

Now,it works in windows with python3.10,but it raise a error  when i use `q` to quit 

![image](https://user-images.githubusercontent.com/6119652/192505730-8713c74b-dd6a-472f-9955-e5ed51ec61fe.png)

>window terminal,powershell7.2.6,python3.10.4

**Comment by blueyed** [comment]
Can you reproduce it with a smaller example?

In general, `BdbQuit` is what is used to quit pdb/bdb, and it might be shown although it should not.

**Comment by brucmao** [comment]
this is my code in quiz.py
```
import pdb

a = 5
b = 10

pdb.set_trace()

c = a + b

print(c)
```
There is an error when i test in terminal
```
❯ python quiz.py
[0] > c:\users\brucm\desktop\quiz.py(8)<module>()
-> c = a + b
(Pdb++) q
Traceback (most recent call last):
  File "C:\Users\brucm\Desktop\quiz.py", line 8, in <module>
    c = a + b
  File "C:\Users\brucm\Desktop\quiz.py", line 8, in <module>
    c = a + b
  File "C:\Users\brucm\scoop\apps\python\current\lib\bdb.py", line 90, in trace_dispatch
    return self.dispatch_line(frame)
  File "C:\Users\brucm\scoop\apps\python\current\lib\bdb.py", line 115, in dispatch_line
    if self.quitting: raise BdbQuit
bdb.BdbQuit
```
another error when I use `run`
```
❯ python quiz.py
[0] > c:\users\brucm\desktop\quiz.py(8)<module>()
-> c = a + b
(Pdb++) run
Traceback (most recent call last):
  File "C:\Users\brucm\Desktop\quiz.py", line 8, in <module>
    c = a + b
  File "C:\Users\brucm\Desktop\quiz.py", line 8, in <module>
    c = a + b
  File "C:\Users\brucm\scoop\apps\python\current\lib\bdb.py", line 90, in trace_dispatch
    return self.dispatch_line(frame)
  File "C:\Users\brucm\scoop\apps\python\current\lib\bdb.py", line 114, in dispatch_line
    self.user_line(frame)
  File "C:\Users\brucm\scoop\apps\python\current\lib\pdb.py", line 262, in user_line
    self.interaction(frame, None)
  File "C:\Users\brucm\scoop\apps\python\current\lib\site-packages\pdb.py", line 231, in interaction
    self._cmdloop()
  File "C:\Users\brucm\scoop\apps\python\current\lib\pdb.py", line 322, in _cmdloop
    self.cmdloop()
  File "C:\Users\brucm\scoop\apps\python\current\lib\cmd.py", line 138, in cmdloop
    stop = self.onecmd(line)
  File "C:\Users\brucm\scoop\apps\python\current\lib\pdb.py", line 422, in onecmd
    return cmd.Cmd.onecmd(self, line)
  File "C:\Users\brucm\scoop\apps\python\current\lib\cmd.py", line 217, in onecmd
    return func(arg)
  File "C:\Users\brucm\scoop\apps\python\current\lib\pdb.py", line 1036, in do_run
    raise Restart
pdb.Restart
```

**Comment by haojue** [comment]
similar issue here, when trying to debug ansible

python -m pdb /usr/bin/ansible-playbook  -i /somepath/inventory/3242/hosts /root/testplay2.yml -v

b /usr/lib/python3.6/site-packages/ansible/executor/task_executor.py:368

```
(Pdb)
An exception occurred during task execution. To see the full traceback, use -vvv. The error was: bdb.BdbQuit
fatal: [172.26.3.242]: FAILED! => {"msg": "Unexpected failure during module execution.", "stdout": ""}
```
