### ISSUE TITLE
rebind_globals causes `Exception` to be unknown

### ISSUE THREAD

**Issue by blueyed** [pdbpp/pdbpp#91]
With https://github.com/python/cpython/pull/6506 I've noticed that pdbpp's
wrapping of `do_debug` causes a NameError for `Exception`:

```
% python t-pdb.py
--Return--
[0] > …/Vcs/cpython/t-pdb.py(1)<module>()->None
-> __import__('pdb').set_trace()
(Pdb++) debug foo(
ENTERING RECURSIVE DEBUGGER
Traceback (most recent call last):
  File "/usr/lib/python3.6/pdb.py", line 1100, in do_debug
    sys.call_tracing(p.run, (arg, globals, locals))
  File "/usr/lib/python3.6/bdb.py", line 431, in run
    cmd = compile(cmd, "<string>", "exec")
  File "<string>", line 1
    foo(
       ^
SyntaxError: unexpected EOF while parsing

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "t-pdb.py", line 1, in <module>
    __import__('pdb').set_trace()
  File "/usr/lib/python3.6/bdb.py", line 55, in trace_dispatch
    return self.dispatch_return(frame, arg)
  File "/usr/lib/python3.6/bdb.py", line 96, in dispatch_return
    self.user_return(frame, arg)
  File "/usr/lib/python3.6/pdb.py", line 293, in user_return
    self.interaction(frame, None)
  File "/usr/lib/python3.6/site-packages/pdb.py", line 250, in interaction
    self.cmdloop()
  File "/usr/lib/python3.6/cmd.py", line 138, in cmdloop
    stop = self.onecmd(line)
  File "/usr/lib/python3.6/pdb.py", line 418, in onecmd
    return cmd.Cmd.onecmd(self, line)
  File "/usr/lib/python3.6/cmd.py", line 217, in onecmd
    return func(arg)
  File "/usr/lib/python3.6/site-packages/pdb.py", line 643, in do_debug
    return orig_do_debug(self, arg)
  File "/usr/lib/python3.6/pdb.py", line 1101, in do_debug
    except Exception as exc:
NameError: name 'Exception' is not defined
```

**Comment by blueyed** [comment]
Fixed by now.
